<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="DatosEspecificos" type="DatosEspecificos"/>
	<xs:complexType name="DatosEspecificos">
		<xs:all>
			<xs:element ref="Resolucion" minOccurs="0"/>
			<xs:element ref="Estado"/>
		</xs:all>
		<xs:attribute name="Id" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:element name="CodigoEstado">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="4"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoEstadoSecundario">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="16"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="LiteralError">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="255"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Estado">
		<xs:complexType>
			<xs:all>
				<xs:element ref="CodigoEstado"/>
				<xs:element ref="CodigoEstadoSecundario" minOccurs="0"/>
				<xs:element ref="LiteralError"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<!-- Resolucion -->
	<xs:element name="Resolucion">
		<xs:complexType>
			<xs:all>
				<xs:element ref="NumeroExpediente">
					<xs:annotation>
						<xs:documentation>Campo que especifica el
número de expediente</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="GradoyNivel">
					<xs:annotation>
						<xs:documentation>Campo que especifica el grado
y nivel de dependencia. 
Los posibles valores que puede tener este elemento son:
- Grado III Nivel 2
- Grado III Nivel 1
- Grado II Nivel 2
- Grado II Nivel 1
- Grado I Nivel 2
- Grado I Nivel 1
- Grado I
- Grado II 
- Grado III </xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="Tipo">
					<xs:annotation>
						<xs:documentation>Campo que especifica el Tipo de dependencia reconocida.

Valores posibles:
- Grado y Nivel
- Grado y Nivel (DF1)

La diferencia de “Grado y Nivel (DF1)” respecto a “Grado y Nivel” es que para los grados y niveles que todavía no aplican, debido a la progresividad que marca la Ley, no se les resuelve el Grado y Nivel como tal sino que se le aplica la Disposición Final Primera de modo que se le reconoce su dependencia pero no se puede seguir gestionando las prestaciones dado que su grado todavía no ha entrado en vigor.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="FechaResolucion">
					<xs:annotation>
						<xs:documentation>Campo que especifica la fecha
en la que se reconoce el grado y nivel de dependencia del Titular consultado.
Formato DD/MM/YYYY</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="EstadoResolucion">
					<xs:annotation>
						<xs:documentation>Campo que especifica el estado de la resolución:
- Firmada
- Recurrida: la resolución ha sido previamente firmada todavía es vigente pero el Recurso o Revisión todavía no ha sido resuelto.
- En trámite
</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="NumeroExpediente">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="100"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="GradoyNivel">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="100"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Tipo">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="100"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FechaResolucion">
		<xs:annotation>
			<xs:documentation>Formato DD/MM/YYYY</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="10"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="EstadoResolucion">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="100"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>
