--------------------------------------------------------
--  GRANTS
--------------------------------------------------------

GRANT SELECT ON ID_APLICACION_SEQUENCE TO WWW_PINBAL;
GRANT SELECT ON ID_AUTORIZACION_CA_SEQ TO WWW_PINBAL;
GRANT SELECT ON ID_AUTORIZACION_CERTIFIC_SEQ TO WWW_PINBAL;
GRANT SELECT ON ID_AUTORIZACION_ORGANISMO_SEQ TO WWW_PINBAL;
GRANT SELECT ON ID_CLAVE_PRIVADA_SEQUENCE TO WWW_PINBAL;
GRANT SELECT ON ID_CLAVE_PUBLICA_SEQUENCE TO WWW_PINBAL;
GRANT SELECT ON ID_EMISOR_SEQUENCE TO WWW_PINBAL;
GRANT SELECT ON ID_ORGANISMO_CESIONARIO_SEQ TO WWW_PINBAL;
GRANT SELECT ON ID_SERVICIO_CESIONARIO_SEQ TO WWW_PINBAL;
GRANT SELECT ON ID_SERVICIO_SEQUENCE TO WWW_PINBAL;
GRANT SELECT ON ACL_CLASS_SEQ TO WWW_PINBAL;
GRANT SELECT ON ACL_ENTRY_SEQ TO WWW_PINBAL;
GRANT SELECT ON ACL_OID_SEQ TO WWW_PINBAL;
GRANT SELECT ON ACL_SID_SEQ TO WWW_PINBAL;
GRANT SELECT ON HIBERNATE_SEQUENCE TO WWW_PINBAL;

GRANT SELECT, UPDATE, INSERT, DELETE ON ACL_CLASS TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON ACL_ENTRY TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON ACL_OBJECT_IDENTITY TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON ACL_SID TO WWW_PINBAL;

GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_CODIGO_ERROR TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_TIPO_MENSAJE TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_CACHE_CERTIFICADOS TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_ESTADO_PETICION TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_MODULO TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_EMISOR_CERTIFICADO TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_CLAVE_PUBLICA TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_ORGANISMO_CESIONARIO TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_CLAVE_PRIVADA TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_SERVICIO TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_MODULO_CONFIGURACION TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_REQ_SECUENCIA_ID_PETICION TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_PETICION_RESPUESTA TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_TRANSMISION TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_TOKEN_DATA TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_PARAMETRO_CONFIGURACION TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_REQ_CESIONARIOS_SERVICIOS TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_REQ_MODULO_PDF TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_REQ_MODULO_PDF_CESIONARIO TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_LOG TO WWW_PINBAL;

GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_AVIS TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_CONFIG_GROUP TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_CONFIG TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_CONFIG_TYPE TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_SERVEI_REGLA TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_SERVEI_REGLA_VALOR_AFC TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_SERVEI_REGLA_VALOR_MOD TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_USUARI TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_ENTITAT TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_ENTITAT_SERVEI TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_ENTITAT_USUARI TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_ORGAN_GESTOR TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_PROCEDIMENT TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_CONSULTA_HIST TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_PROCEDIMENT_SERVEI TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_CONSULTA TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_SERVEI_BUS TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_SERVEI_CAMP_GRUP TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_SERVEI_CAMP TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_SERVEI_CONFIG TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_SERVEI_JUSTIF_CAMP TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_EXPLOT_TEMPS TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_EXPLOT_CONSULTA_DIM TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_EXPLOT_CONSULTA_FET TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_CONSULTA_DO TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_CONSULTA_HIST_DO TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_CONSULTA_LIST TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_CONSULTA_HIST_LIST TO WWW_PINBAL;


--------------------------------------------------------
--  LOBS
--------------------------------------------------------

ALTER TABLE CORE_ORGANISMO_CESIONARIO move lob (LOGO) store as CORE_ORGCES_LOGO_LOB (tablespace PINBAL_LOB);
ALTER TABLE CORE_TRANSMISION move lob (XMLTRANSMISION) store as CORE_TRANS_XMLTRANSMISION_LOB (tablespace PINBAL_LOB);
ALTER TABLE CORE_TOKEN_DATA move lob (DATOS) store as CORE_TOKENDATA_DATOS_LOB (tablespace PINBAL_LOB);
ALTER TABLE CORE_LOG move lob (MENSAJE) store as CORE_LOG_MENSAJE_LOB (tablespace PINBAL_LOB);
ALTER TABLE PBL_SERVEI_CAMP_GRUP move lob (AJUDA) store as PBL_SRVCMPGRUP_AJUDA_LOB (tablespace PINBAL_LOB);
ALTER TABLE PBL_SERVEI_CONFIG move lob (AJUDA) store as PBL_SERVEI_CONFIG_AJUDA_LOB (tablespace PINBAL_LOB);
ALTER TABLE PBL_SERVEI_CONFIG move lob (FITXER_AJUDA_CONTINGUT) store as PBL_SERVEI_CONFIG_CONT_LOB (tablespace PINBAL_LOB);
ALTER TABLE PBL_CONSULTA move lob (DADES_ESPECIFIQUES) store as PBL_CONSULTA_DADESP_LOB (tablespace PINBAL_LOB);
ALTER TABLE PBL_CONSULTA_HIST move lob (DADES_ESPECIFIQUES) store as PBL_CONSULTA_HIST_DADESP_LOB (tablespace PINBAL_LOB);