--------------------------------------------------------
--  Configuracion de esquema scsp requirente 
--------------------------------------------------------

--------------------------------------------------------
--  Inserts for Table CORE_PARAMETRO_CONFIGURACION
--	Se deben sustituir los valores puestos a null por los valores reales de cada configuración (2a columna)
--	Consulte el documento del modelo de datos y el de configuración para ver que valores puede tomar cada parámetro
--------------------------------------------------------
-- Valors d'exemple (PRE):
-- NOMBRE    											VALOR                                                                   VALORS POSSIBLES
-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- afirma.autenticacion.aliasSignerCert             |   preprod-dgmad                                                       |
-- afirma.enabled                                   |   false                                                               |
-- afirma.idAplicacion                              |   none                                                                |
-- afirma.modoValidacion                            |   none                                                                |
-- afirma.url                                       |   none                                                                |
-- almacenamiento.ficheros                          |   /app/caib/pinbal                                                    |
-- almacenamiento.transmisiones                     |   1                                                                   |
-- axis2.client.xml                                 |   /axis2/axis2.xml                                                    |
-- axis2.client.repository                          |   /axis2/                                                             |
-- core_log.enabled                                 |   false                                                               |
-- custom.cert.validation.class                     |   es.scsp.common.certificates.revocation.IgnoreRevocationManager      |
-- imagen.logo                                      |   logo.jpg                                                            |
-- keystoreFile                                     |   file:/app/caib/crypto/preprod-dgmad.jks                             |
-- keystoreType                                     |   jks                                                                 |
-- logDinamico.enabled                              |   false                                                               |
-- nivelTraza                                       |   INFO                                                                |
-- nombre.ministerio                                |   Ministerio de Asuntos Económicos y Transformación Digital           |
-- pathLogs                                         |   /app/caib/pinbal/logs                                               |
-- periodo.validacion.certificados                  |   24                                                                  |
-- polling.enabled                                  |   true                                                                |
-- prefijo.idpeticion                               |   PINBAL                                                              |
-- task.polling.espera                              |   1                                                                   |
-- task.polling.intervalo                           |   5                                                                   |
-- task.polling.size                                |   50                                                                  |
-- tipoId                                           |   long                                                                |
-- validacion.formatoFirma                          |   permisivo                                                           |
-- version.datamodel.scsp                           |   3.5.0                                                               |
-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('afirma.autenticacion.aliasSignerCert', null,                                                                   'Alias del certificado con el que firmamos la peticiones para @Firma');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('afirma.enabled',                       'true',                                                                 'Parámetro que indica si @Firma está activo');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('afirma.idAplicacion',                  null,                                                                   'Id de aplicación para enviar a @Firma');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('afirma.modoValidacion',                2,                                                                      'Modo de validación del certificado con @Firma');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('afirma.url',                           'https://des-afirma.redsara.es/afirmaws/services/ValidarCertificado',   'URL de @Firma');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('almacenamiento.ficheros',              null,                                                                   'Directorio donde se guardan los ficheros de las peticiones');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('almacenamiento.transmisiones',         1,                                                                      'Parámetro que indica si se guardarán los nodos de las transmisiones');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('axis2.client.repository',              '/axis2/',                                                              'Path donde se encuentra el archivo axis2.xml');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('axis2.client.xml',                     '/axis2/axis2.xml',                                                     'Dirección relativa del archivo axis2.xml');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('cif.emisor',                           null,                                                                   'CIF del Emisor');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('core_log.enabled',                     null,                                                                   'Parámetro que indica si se guardarán trazas en CORE_LOG de los errores ocurridos');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('custom.cert.validation.class',         'none',                                                                 'Clase propia de validación de certificados');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('imagen.logo',                          'logo.jpg',                                                             'Indica la imagen utilizada en los justificantes PDF');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('keystoreFile',                         null,                                                                   'Ruta del fichero keystore');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('keystorePass',                         null,                                                                   'Password del keystore');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('keystoreType',                         'jks',                                                                  'Tipo de keystore');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('logDinamico.enabled',                  null,                                                                   'Parámetro que indica si se cargará de BBDD la configuración de logs o de fichero');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('nivelTraza',                           'DEBUG',                                                                'Nivel de traza a mostrar en los logs');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('nombre.emisor',                        null,                                                                   'Nombre del Emisor');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('nombre.ministerio',                    'Ministerio de Asuntos Económicos y Transformación Digital',            'Nombre del Ministerio');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('pathLogs',                             null,                                                                   'Ruta del fichero donde guardaremos los logs');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('periodo.validacion.certificados',      24,                                                                     'Periodo de validez del certificado en caché');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('polling.enabled',                      'true',                                                                 'Valor que indica si el Polling estará o no activado');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('prefijo.idpeticion',                   null,                                                                   'Prefijo utilizado para la generación del id de petición');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('prefijo.idtransmision',                null,                                                                   'Cuando no haya indicado un prefijo asociado al servicio y este si está definido se utilizará este para la generación del id de transmisión.');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('task.polling.espera',                  5,                                                                      'Valor que indica el tiempoq ue tardará el Polling en ser ejecutado por primera vez.Se expresa en minutos.');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('task.polling.intervalo',               1440,                                                                   'valor que indica el tiempo de ejecución del Polling');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('tipoId',                               'long',                                                                 'Longitud del identificador de la petición');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('validacion.formatoFirma',              'permisivo',                                                            'Formato de validación de firma');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('validate.nif.emisor.enabled',          'true',                                                                 'Flag que indica si se valida el valor del nodo <NifEmisor> de la petición');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('version.datamodel.scsp',               '4.25.0',                                                                'Especifica la versión del modelo de datos actual');


--------------------------------------------------------
--  Inserts for Table organismo_cesionario
-- Se debe modificar según necesidades y según los datos propios del organismo
--------------------------------------------------------
INSERT INTO CORE_ORGANISMO_CESIONARIO (ID,NOMBRE,CIF,FECHAALTA,BLOQUEADO,LOGO) VALUES ((ID_ORGANISMO_CESIONARIO_SEQ.nextval),NULL,NULL,SYSDATE,'0',NULL);

--------------------------------------------------------
--  Inserts for Table CORE_CLAVE_PRIVADA
-- Se debe modificar según necesidades y según la configuración del almacén de claves utilizado
--------------------------------------------------------
INSERT INTO CORE_CLAVE_PRIVADA (ID,ALIAS,NOMBRE,PASSWORD,NUMEROSERIE,ORGANISMO,FECHAALTA,INTEROPERABILIDAD) VALUES ((ID_CLAVE_PRIVADA_SEQUENCE.nextval),null,null,null,null,(ID_ORGANISMO_CESIONARIO_SEQ.currval),SYSDATE, 0);

--------------------------------------------------------
--  Inserts for Table CORE_CLAVE_PUBLICA
-- Se debe modificar según necesidades y según la configuración del almacén de claves utilizado
--------------------------------------------------------
INSERT INTO CORE_CLAVE_PUBLICA (ID,ALIAS,NOMBRE,NUMEROSERIE,FECHAALTA) VALUES ((ID_CLAVE_PUBLICA_SEQUENCE.nextval),null,null,null,SYSDATE);

--------------------------------------------------------
--  Inserts for Table CORE_EMISOR_CERTIFICADO
-- Se deben eliminar los inserts correspondientes a organismos de los que no vamos a consumir servicios
--------------------------------------------------------

INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2826053G','Catastro');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q2819009H','SPEE-INEM');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q2827003A','TGSS');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q2826000H','AEAT');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2818001F','Educacion');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2833002E','MINHAP');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q2827004I','IMSERSO');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q2827002C','INSS');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2813001A','RRCC Justicia');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2826013A','DG. Seguros');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S3100000C','Gobierno de Navarra');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2812001B','MAEC');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q2826039F','INE');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2816015H','DGP');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q2863008E','C.G.Notariado');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S0711001H','Govern de les Illes Balears');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2801109F','Dirección General de Ordenación del Juego');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2800665H','SEPBLAC');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q2812007I','INSTITUTO CERVANTES');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q2816003D','Dirección General de Tráfico');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2826015F','IGAE');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q2861001B','MUFACE');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'G81093072','CRUE');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S4833001C','País Vasco');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q0700448D','IMAS');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2800568D','Min. de Asuntos Econ. y Transformación Digital');

--------------------------------------------------------
--  Inserts for Table CORE_MODULO
-- Se debe modificar según necesidades los parámetros '1' Activado por defecto o '0' desactivado
--------------------------------------------------------
INSERT INTO CORE_MODULO (NOMBRE,DESCRIPCION,ACTIVOENTRADA,ACTIVOSALIDA) VALUES ('AlmacenarBaseDatos','AlmacenarBaseDatos',1,1);
INSERT INTO CORE_MODULO (NOMBRE,DESCRIPCION,ACTIVOENTRADA,ACTIVOSALIDA) VALUES ('ValidarCertificado','ValidarCertificado',1,0);
INSERT INTO CORE_MODULO (NOMBRE,DESCRIPCION,ACTIVOENTRADA,ACTIVOSALIDA) VALUES ('AlmacenarFichero','AlmacenarFichero',1,1);
INSERT INTO CORE_MODULO (NOMBRE,DESCRIPCION,ACTIVOENTRADA,ACTIVOSALIDA) VALUES ('ValidarEsquema','ValidarEsquema',1,1);
INSERT INTO CORE_MODULO (NOMBRE,DESCRIPCION,ACTIVOENTRADA,ACTIVOSALIDA) VALUES ('AlmacenarFicheroPlain','AlmacenarFicheroPlain',1,1);

--------------------------------------------------------
--  Inserts for Table PBL_CONFIG
    -- Se deben modificar pas propiedades de tipo DATABASE segon las necesidades
--------------------------------------------------------
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.xsd.base.path',                                                                            '/app/caib/pinbal/xsd',                                                                                                                                                                                    'propietat.xsd.base.path',                                                                                  'GENERAL',          0,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.optimitzar.transaccions.nova.consulta',                                                    'true',                                                                                                                                                                                                    'propietat.optimitzar.transaccions.nova.consulta',                                                          'GENERAL',          1,  'DATABASE', 'BOOL');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.entitat.accio.esborrar.activa',                                                            'true',                                                                                                                                                                                                    'propietat.entitat.accio.esborrar.activa',                                                                  'OPCIONS_BORRAR',   0,  'DATABASE', 'BOOL');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.procediment.accio.esborrar.activa',                                                        'true',                                                                                                                                                                                                    'propietat.procediment.accio.esborrar.activa',                                                              'OPCIONS_BORRAR',   1,  'DATABASE', 'BOOL');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.justificant.extensio.sortida',                                                             'pdf',                                                                                                                                                                                                     'propietat.justificant.extensio.sortida',                                                                   'JUSTIFICANT',      0,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.justificant.signar.i.custodiar',                                                           'true',                                                                                                                                                                                                    'propietat.justificant.signar.i.custodiar',                                                                 'JUSTIFICANT',      1,  'DATABASE', 'BOOL');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.justificant.convertir.pdfa',                                                               'true',                                                                                                                                                                                                    'propietat.justificant.convertir.pdfa',                                                                     'JUSTIFICANT',      2,  'DATABASE', 'BOOL');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.justificant.recobriment.generar',                                                          'false',                                                                                                                                                                                                   'propietat.justificant.recobriment.generar',                                                                'JUSTIFICANT',      3,  'DATABASE', 'BOOL');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.conversio.tipus',                                                                          'xdocreport',                                                                                                                                                                                              'propietat.conversio.tipus',                                                                                'CONVERSIO',        0,  'DATABASE', 'CONVERSIO_TIPUS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.conversio.open.office.host',                                                               'sdesooflin1.caib.es',                                                                                                                                                                                     'propietat.conversio.open.office.host',                                                                     'CONVERSIO',        1,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.conversio.open.office.port',                                                               '8100',                                                                                                                                                                                                    'propietat.conversio.open.office.port',                                                                     'CONVERSIO',        2,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.mapeig.rol.PBL_ADMIN',                                                                     'ROLE_ADMIN',                                                                                                                                                                                              'propietat.mapeig.rol.PBL_ADMIN',                                                                           'MAPEIG',           0,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.mapeig.rol.PBL_REPRES',                                                                    'ROLE_REPRES',                                                                                                                                                                                             'propietat.mapeig.rol.PBL_REPRES',                                                                          'MAPEIG',           1,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.mapeig.rol.PBL_DELEG',                                                                     'ROLE_DELEG',                                                                                                                                                                                              'propietat.mapeig.rol.PBL_DELEG',                                                                           'MAPEIG',           2,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.mapeig.rol.PBL_AUDIT',                                                                     'ROLE_AUDIT',                                                                                                                                                                                              'propietat.mapeig.rol.PBL_AUDIT',                                                                           'MAPEIG',           3,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.mapeig.rol.PBL_SUPERAUD',                                                                  'ROLE_SUPERAUD',                                                                                                                                                                                           'propietat.mapeig.rol.PBL_SUPERAUD',                                                                        'MAPEIG',           4,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.mapeig.rol.PBL_WS',                                                                        'ROLE_WS',                                                                                                                                                                                                 'propietat.mapeig.rol.PBL_WS',                                                                              'MAPEIG',           5,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.mapeig.rol.tothom',                                                                        'ROLE_DELEG',                                                                                                                                                                                              'propietat.mapeig.rol.tothom',                                                                              'MAPEIG',           6,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.recobriment.base.url',                                                                     'http://spreapplin1.caib.es:18080/pinbalrec',                                                                                                                                                              'propietat.recobriment.base.url',                                                                           'RECOBRIMENT',      0,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.recobriment.datos.especificos.processar',                                                  'true',                                                                                                                                                                                                    'propietat.recobriment.datos.especificos.processar',                                                        'RECOBRIMENT',      1,  'DATABASE', 'BOOL');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.recobriment.datos.especificos.incloure.ns',                                                'false',                                                                                                                                                                                                   'propietat.recobriment.datos.especificos.incloure.ns',                                                      'RECOBRIMENT',      2,  'DATABASE', 'BOOL');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.email.remitent',                                                                           'pinbal@limit.es',                                                                                                                                                                                         'propietat.email.remitent',                                                                                 'EMAIL',            0,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.email.footer',                                                                             'PINBAL Dev - Govern de les Illes Balears',                                                                                                                                                                'propietat.email.footer',                                                                                   'EMAIL',            1,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.dades.usuari.class',                                                                'es.caib.pinbal.plugins.caib.DadesUsuariPluginJdbc',                                                                                                                                                       'propietat.plugin.dades.usuari.class',                                                                      'USUARIS',          0,  'DATABASE', 'USUARIS_CLASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.dades.usuari.jdbc.datasource.jndi.name',                                            'java:es.caib.seycon.db.wl',                                                                                                                                                                               'propietat.plugin.dades.usuari.jdbc.datasource.jndi.name',                                                  'USUARIS',          1,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.dades.usuari.jdbc.query.codi',                                                      'select usu_codi, usu_nom, usu_nif, usu_codi | |''@caib.es'' from sc_wl_usuari where usu_codi = :codi',                                                                                                    'propietat.plugin.dades.usuari.jdbc.query.codi',                                                            'USUARIS',          2,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.dades.usuari.jdbc.query.nif',                                                       'select usu_codi, usu_nom, usu_nif, usu_codi || ''@caib.es'' from sc_wl_usuari where usu_nif = :nif',                                                                                                      'propietat.plugin.dades.usuari.jdbc.query.nif',                                                             'USUARIS',          3,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.dades.usuari.jdbc.query.rols',                                                      'select ugr_codgru from sc_wl_usugru where ugr_codusu=:codi',                                                                                                                                              'propietat.plugin.dades.usuari.jdbc.query.rols',                                                            'USUARIS',          4,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.dades.usuari.jdbc.query.grup',                                                      'select usu_codi, usu_nom, usu_nif, usu_codi||''@caib.es'' from sc_wl_usuari u, sc_wl_usugru g where g.ugr_codgru=:grup and g.ugr_codusu=u.usu_cod',                                                       'propietat.plugin.dades.usuari.jdbc.query.grup',                                                            'USUARIS',          5,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.dades.usuari.jdbc.query.any',                                                       'select usu_codi, usu_nom, usu_nif, usu_codi||''@caib.es'' from sc_wl_usuari where usu_codi like ''%'' || :text || ''%'' or usu_nif like ''%'' || :text || ''%'' or usu_nom like ''%'' || :text || ''%''', 'propietat.plugin.dades.usuari.jdbc.query.any',                                                             'USUARIS',          6,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.signatura.class',                                                                   'es.caib.pinbal.plugins.caib.SignaturaPluginCaib',                                                                                                                                                         'propietat.plugin.signatura.class',                                                                         'SIGNATURA',        0,  'DATABASE', 'SIGNATURA_CLASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.signatura.caib.certificat.alias',                                                   'CERTIFICAT DE DEV DE LA DGMAD',                                                                                                                                                                           'propietat.plugin.signatura.caib.certificat.alias',                                                         'SIGNATURA',        1,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.signatura.caib.certificat.password',                                                '********',                                                                                                                                                                                                'propietat.plugin.signatura.caib.certificat.password',                                                      'SIGNATURA',        2,  'FILE',     'PASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.signatura.caib.content.type',                                                       null,                                                                                                                                                                                                      'propietat.plugin.signatura.caib.content.type',                                                             'SIGNATURA',        3,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.class',                                                               'es.caib.pinbal.plugins.caib.FirmaSimpleServidorPluginPortafib',                                                                                                                                           'propietat.plugin.firmaservidor.class',                                                                     'FIRMA_SERVIDOR',   0,  'DATABASE', 'FIRMA_SERVIDOR_CLASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.portafib.plugins.signatureserver.portafib.api_passarela_url',         'https://proves.caib.es/portafib/ws/v1/PortaFIBPassarelaDeFirmaEnServidor',                                                                                                                                'propietat.plugin.firmaservidor.portafib.plugins.signatureserver.portafib.api_passarela_url',               'FIRMA_SERVIDOR',   1,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.portafib.plugins.signatureserver.portafib.api_passarela_username',    '$pinbal_portafib_pre',                                                                                                                                                                                    'propietat.tasca.plugin.firmaservidor.portafib.plugins.signatureserver.portafib.api_passarela_username',    'FIRMA_SERVIDOR',   2,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.portafib.plugins.signatureserver.portafib.api_passarela_password',    '********',                                                                                                                                                                                                'propietat.plugin.firmaservidor.portafib.plugins.signatureserver.portafib.api_passarela_password',          'FIRMA_SERVIDOR',   3,  'FILE',     'PASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.portafib.username',                                                   'preprod-dgmad',                                                                                                                                                                                           'propietat.plugin.firmaservidor.portafib.username',                                                         'FIRMA_SERVIDOR',   4,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.portafib.location',                                                   'Palma',                                                                                                                                                                                                   'propietat.plugin.firmaservidor.portafib.location',                                                         'FIRMA_SERVIDOR',   5,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.portafib.signerEmail',                                                'suport@caib.es',                                                                                                                                                                                          'propietat.plugin.firmaservidor.portafib.signerEmail',                                                      'FIRMA_SERVIDOR',   6,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.portafib.endpoint',                                                   'https://proves.caib.es/portafib/common/rest/apifirmaenservidorsimple/v1/',                                                                                                                                'propietat.plugin.firmaservidor.portafib.endpoint',                                                         'FIRMA_SERVIDOR',   7,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.portafib.auth.username',                                              '$pinbal_portafib_pre',                                                                                                                                                                                    'propietat.plugin.firmaservidor.portafib.auth.username',                                                    'FIRMA_SERVIDOR',   8,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.portafib.auth.password',                                              '********',                                                                                                                                                                                                'propietat.plugin.firmaservidor.portafib.auth.password',                                                    'FIRMA_SERVIDOR',   9,  'FILE',     'PASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.portafib.perfil',                                                     'PADES',                                                                                                                                                                                                   'propietat.plugin.firmaservidor.portafib.perfil',                                                           'FIRMA_SERVIDOR',   10, 'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.custodia.class',                                                                    'es.caib.pinbal.plugins.caib.CustodiaPluginCaib',                                                                                                                                                          'propietat.plugin.custodia.class',                                                                          'CUSTODIA',         0,  'DATABASE', 'CUSTODIA_CLASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.custodia.caib.url',                                                                 'https://proves.caib.es/signatura/services/CustodiaDocumentos',                                                                                                                                            'propietat.plugin.custodia.caib.url',                                                                       'CUSTODIA',         1,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.custodia.caib.username',                                                            'PINBAL',                                                                                                                                                                                                  'propietat.plugin.custodia.caib.username',                                                                  'CUSTODIA',         2,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.custodia.caib.password',                                                            '********',                                                                                                                                                                                                'propietat.plugin.custodia.caib.password',                                                                  'CUSTODIA',         3,  'FILE',     'PASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.custodia.caib.tipus.document',                                                      'PBL_JUSTIFICANT_VERIFICACIO_DADES',                                                                                                                                                                       'propietat.plugin.custodia.caib.tipus.document',                                                            'CUSTODIA',         4,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.custodia.caib.verificacio.url.bas',                                                 null,                                                                                                                                                                                                      'propietat.plugin.custodia.caib.verificacio.url.bas',                                                       'CUSTODIA',         5,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.class',                                                                       'es.caib.plugins.arxiu.caib.ArxiuPluginCaib',                                                                                                                                                              'propietat.plugin.arxiu.class',                                                                             'ARXIU',            0,  'DATABASE', 'ARXIU_CLASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.caib.base.url',                                                               'https://esbse.caib.es:4430/esb',                                                                                                                                                                          'propietat.plugin.arxiu.caib.base.url',                                                                     'ARXIU',            1,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.caib.aplicacio.codi',                                                         'PINBAL',                                                                                                                                                                                                  'propietat.plugin.arxiu.caib.aplicacio.codi',                                                               'ARXIU',            2,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.caib.usuari',                                                                 'pinbal',                                                                                                                                                                                                  'propietat.plugin.arxiu.caib.usuari',                                                                       'ARXIU',            3,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.caib.contrasenya',                                                            '********',                                                                                                                                                                                                'propietat.plugin.arxiu.caib.contrasenya',                                                                  'ARXIU',            4,  'FILE',     'PASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.caib.csv_generation_definition',                                              'CSV_DEF',                                                                                                                                                                                                 'propietat.plugin.arxiu.caib.csv_generation_definition',                                                    'ARXIU',            5,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.caib.conversio.imprimible.url',                                               'https://se.caib.es/concsvapi/interna/printable/uuid',                                                                                                                                                     'propietat.plugin.arxiu.caib.conversio.imprimible.url',                                                     'ARXIU',            6,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.caib.conversio.imprimible.usuari',                                            '$pinbal_concsv',                                                                                                                                                                                          'propietat.tasca.plugin.arxiu.caib.conversio.imprimible.usuari',                                            'ARXIU',            7,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.caib.conversio.imprimible.contrasenya',                                       '********',                                                                                                                                                                                                'propietat.plugin.arxiu.caib.conversio.imprimible.contrasenya',                                             'ARXIU',            8,  'FILE',     'PASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.caib.timeout.connect',                                                        '20000',                                                                                                                                                                                                   'propietat.plugin.arxiu.caib.timeout.connect',                                                              'ARXIU',            9,  'DATABASE', 'INT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.caib.timeout.read',                                                           '20000',                                                                                                                                                                                                   'propietat.plugin.arxiu.caib.timeout.read',                                                                 'ARXIU',            10, 'DATABASE', 'INT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.serie.documental',                                                            'SPINBAL',                                                                                                                                                                                                 'propietat.plugin.arxiu.serie.documental',                                                                  'ARXIU',            11, 'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.unitats.organitzatives.class',                                                      'es.caib.pinbal.plugin.caib.unitat.UnitatsOrganitzativesPluginDir3',                                                                                                                                       'propietat.plugin.unitats.organitzatives.class',                                                            'UNITATS',          0,  'DATABASE', 'UNITATS_CLASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.unitats.organitzatives.dir3.service.url',                                           'http://dev.caib.es/dir3caib',                                                                                                                                                                             'propietat.plugin.unitats.organitzatives.dir3.service.url',                                                 'UNITATS',          1,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.unitats.organitzatives.dir3.service.username',                                      '$pinbal_dir3caib',                                                                                                                                                                                        'propietat.plugin.unitats.organitzatives.dir3.service.username',                                            'UNITATS',          2,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.unitats.organitzatives.dir3.service.password',                                      '********',                                                                                                                                                                                                'propietat.plugin.unitats.organitzatives.dir3.service.password',                                            'UNITATS',          3,  'FILE',     'PASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.unitats.organitzatives.dir3.service.log.actiu',                                     'true',                                                                                                                                                                                                    'propietat.plugin.unitats.organitzatives.dir3.service.log.actiu',                                           'UNITATS',          4,  'DATABASE', 'BOOL');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.unitats.cerca.dir3.service.url',                                                    'https://dev.caib.es/dir3caib/rest/busqueda/organismos',                                                                                                                                                   'propietat.plugin.unitats.cerca.dir3.service.url',                                                          'UNITATS',          5,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.tasca.auto.arxivar.consultes.cron',                                                        '0 0 1 * * ?',                                                                                                                                                                                             'propietat.tasca.auto.arxivar.consultes.cron',                                                              'HISTORIC',         0,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.tasca.auto.arxivar.antiguetat.dies',                                                       '180',                                                                                                                                                                                                     'propietat.tasca.auto.arxivar.antiguetat.dies',                                                             'HISTORIC',         1,  'DATABASE', 'INT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.tasca.auto.comprovacio.repeticio',                                                         '10000',                                                                                                                                                                                                   'propietat.tasca.auto.comprovacio.repeticio',                                                               'TASQUES',          0,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.tasca.auto.justificant.repeticio',                                                         null,                                                                                                                                                                                                      'propietat.tasca.auto.justificant.repeticio',                                                               'TASQUES',          1,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.tasca.auto.exp.tancar.cron',                                                               null,                                                                                                                                                                                                      'propietat.tasca.auto.exp.tancar.cron',                                                                     'TASQUES',          2,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.tasca.auto.email.report.estat.cron',                                                       '0 0 22 * * *',                                                                                                                                                                                            'propietat.tasca.auto.email.report.estat.cron',                                                             'TASQUES',          3,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.tasca.auto.generar.explotacio.cron',                                                       '0 30 0 * * ?',                                                                                                                                                                                            'propietat.tasca.auto.generar.explotacio.cron',                                                             'TASQUES',          4,  'DATABASE', 'TEXT');

--------------------------------------------------------
--  Inserts for Table PBL_ENTITAT
--------------------------------------------------------
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1, 'GOVERN', 'Govern de les Illes Balears', null, 'S0711001H', 1, 1, 'A04003003', 'admin', SYSDATE, 'admin', SYSDATE, 3);
