--------------------------------------------------------
--  Configuracion de esquema scsp requirente 
--------------------------------------------------------

--------------------------------------------------------
--  Inserts for Table CORE_PARAMETRO_CONFIGURACION
--	Se deben sustituir los valores puestos a null por los valores reales de cada configuración (2a columna)
--	Consulte el documento del modelo de datos y el de configuración para ver que valores puede tomar cada parámetro
--------------------------------------------------------
-- Valors d'exemple (PRE):
-- NOMBRE    											VALOR                                                                   VALORS POSSIBLES
-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- afirma.autenticacion.aliasSignerCert             |   preprod-dgmad                                                       |
-- afirma.enabled                                   |   false                                                               |
-- afirma.idAplicacion                              |   none                                                                |
-- afirma.modoValidacion                            |   none                                                                |
-- afirma.url                                       |   none                                                                |
-- almacenamiento.ficheros                          |   /app/caib/pinbal                                                    |
-- almacenamiento.transmisiones                     |   1                                                                   |
-- axis2.client.xml                                 |   /axis2/axis2.xml                                                    |
-- axis2.client.repository                          |   /axis2/                                                             |
-- core_log.enabled                                 |   false                                                               |
-- custom.cert.validation.class                     |   es.scsp.common.certificates.revocation.IgnoreRevocationManager      |
-- imagen.logo                                      |   logo.jpg                                                            |
-- keystoreFile                                     |   file:/app/caib/crypto/preprod-dgmad.jks                             |
-- keystoreType                                     |   jks                                                                 |
-- logDinamico.enabled                              |   false                                                               |
-- nivelTraza                                       |   INFO                                                                |
-- nombre.ministerio                                |   Ministerio de Asuntos Económicos y Transformación Digital           |
-- pathLogs                                         |   /app/caib/pinbal/logs                                               |
-- periodo.validacion.certificados                  |   24                                                                  |
-- polling.enabled                                  |   true                                                                |
-- prefijo.idpeticion                               |   PINBAL                                                              |
-- task.polling.espera                              |   1                                                                   |
-- task.polling.intervalo                           |   5                                                                   |
-- task.polling.size                                |   50                                                                  |
-- tipoId                                           |   long                                                                |
-- validacion.formatoFirma                          |   permisivo                                                           |
-- version.datamodel.scsp                           |   3.5.0                                                               |
-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('afirma.autenticacion.aliasSignerCert', null,                                                                   'Alias del certificado con el que firmamos la peticiones para @Firma');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('afirma.enabled',                       'true',                                                                 'Parámetro que indica si @Firma está activo');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('afirma.idAplicacion',                  null,                                                                   'Id de aplicación para enviar a @Firma');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('afirma.modoValidacion',                2,                                                                      'Modo de validación del certificado con @Firma');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('afirma.url',                           'https://des-afirma.redsara.es/afirmaws/services/ValidarCertificado',   'URL de @Firma');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('almacenamiento.ficheros',              null,                                                                   'Directorio donde se guardan los ficheros de las peticiones');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('almacenamiento.transmisiones',         1,                                                                      'Parámetro que indica si se guardarán los nodos de las transmisiones');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('axis2.client.repository',              '/axis2/',                                                              'Path donde se encuentra el archivo axis2.xml');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('axis2.client.xml',                     '/axis2/axis2.xml',                                                     'Dirección relativa del archivo axis2.xml');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('cif.emisor',                           null,                                                                   'CIF del Emisor');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('core_log.enabled',                     null,                                                                   'Parámetro que indica si se guardarán trazas en CORE_LOG de los errores ocurridos');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('custom.cert.validation.class',         'none',                                                                 'Clase propia de validación de certificados');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('imagen.logo',                          'logo.jpg',                                                             'Indica la imagen utilizada en los justificantes PDF');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('keystoreFile',                         null,                                                                   'Ruta del fichero keystore');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('keystorePass',                         null,                                                                   'Password del keystore');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('keystoreType',                         'jks',                                                                  'Tipo de keystore');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('logDinamico.enabled',                  null,                                                                   'Parámetro que indica si se cargará de BBDD la configuración de logs o de fichero');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('nivelTraza',                           'DEBUG',                                                                'Nivel de traza a mostrar en los logs');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('nombre.emisor',                        null,                                                                   'Nombre del Emisor');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('nombre.ministerio',                    'Ministerio de Asuntos Económicos y Transformación Digital',            'Nombre del Ministerio');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('pathLogs',                             null,                                                                   'Ruta del fichero donde guardaremos los logs');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('periodo.validacion.certificados',      24,                                                                     'Periodo de validez del certificado en caché');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('polling.enabled',                      'true',                                                                 'Valor que indica si el Polling estará o no activado');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('prefijo.idpeticion',                   null,                                                                   'Prefijo utilizado para la generación del id de petición');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('prefijo.idtransmision',                null,                                                                   'Cuando no haya indicado un prefijo asociado al servicio y este si está definido se utilizará este para la generación del id de transmisión.');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('task.polling.espera',                  5,                                                                      'Valor que indica el tiempoq ue tardará el Polling en ser ejecutado por primera vez.Se expresa en minutos.');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('task.polling.intervalo',               1440,                                                                   'valor que indica el tiempo de ejecución del Polling');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('tipoId',                               'long',                                                                 'Longitud del identificador de la petición');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('validacion.formatoFirma',              'permisivo',                                                            'Formato de validación de firma');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('validate.nif.emisor.enabled',          'true',                                                                 'Flag que indica si se valida el valor del nodo <NifEmisor> de la petición');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('version.datamodel.scsp',               '4.25.0',                                                                'Especifica la versión del modelo de datos actual');


--------------------------------------------------------
--  Inserts for Table organismo_cesionario
-- Se debe modificar según necesidades y según los datos propios del organismo
--------------------------------------------------------
INSERT INTO CORE_ORGANISMO_CESIONARIO (ID,NOMBRE,CIF,FECHAALTA,BLOQUEADO,LOGO) VALUES ((ID_ORGANISMO_CESIONARIO_SEQ.nextval),NULL,NULL,SYSDATE,'0',NULL);


--------------------------------------------------------
--  Inserts for Table CORE_CLAVE_PRIVADA
-- Se debe modificar según necesidades y según la configuración del almacén de claves utilizado
--------------------------------------------------------
INSERT INTO CORE_CLAVE_PRIVADA (ID,ALIAS,NOMBRE,PASSWORD,NUMEROSERIE,ORGANISMO,FECHAALTA,INTEROPERABILIDAD) VALUES ((ID_CLAVE_PRIVADA_SEQUENCE.nextval),null,null,null,null,(ID_ORGANISMO_CESIONARIO_SEQ.currval),SYSDATE, 0);


--------------------------------------------------------
--  Inserts for Table CORE_CLAVE_PUBLICA
-- Se debe modificar según necesidades y según la configuración del almacén de claves utilizado
--------------------------------------------------------
INSERT INTO CORE_CLAVE_PUBLICA (ID,ALIAS,NOMBRE,NUMEROSERIE,FECHAALTA) VALUES ((ID_CLAVE_PUBLICA_SEQUENCE.nextval),null,null,null,SYSDATE);


--------------------------------------------------------
--  Inserts for Table CORE_EMISOR_CERTIFICADO
-- Se deben eliminar los inserts correspondientes a organismos de los que no vamos a consumir servicios
--------------------------------------------------------

INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2826053G','Catastro');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q2819009H','SPEE-INEM');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q2827003A','TGSS');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q2826000H','AEAT');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2818001F','Educacion');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2833002E','MINHAP');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q2827004I','IMSERSO');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q2827002C','INSS');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2813001A','RRCC Justicia');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2826013A','DG. Seguros');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S3100000C','Gobierno de Navarra');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2812001B','MAEC');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q2826039F','INE');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2816015H','DGP');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q2863008E','C.G.Notariado');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S0711001H','Govern de les Illes Balears');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2801109F','Dirección General de Ordenación del Juego');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2800665H','SEPBLAC');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q2812007I','INSTITUTO CERVANTES');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q2816003D','Dirección General de Tráfico');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2826015F','IGAE');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q2861001B','MUFACE');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'G81093072','CRUE');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S4833001C','País Vasco');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'Q0700448D','IMAS');
INSERT INTO CORE_EMISOR_CERTIFICADO (ID,CIF,NOMBRE) VALUES ((ID_EMISOR_SEQUENCE.nextval),'S2800568D','Min. de Asuntos Econ. y Transformación Digital');

--------------------------------------------------------
--  Inserts for Table CORE_MODULO
-- Se debe modificar según necesidades los parámetros '1' Activado por defecto o '0' desactivado
--------------------------------------------------------
INSERT INTO CORE_MODULO (NOMBRE,DESCRIPCION,ACTIVOENTRADA,ACTIVOSALIDA) VALUES ('AlmacenarBaseDatos','AlmacenarBaseDatos',1,1);
INSERT INTO CORE_MODULO (NOMBRE,DESCRIPCION,ACTIVOENTRADA,ACTIVOSALIDA) VALUES ('ValidarCertificado','ValidarCertificado',1,0);
INSERT INTO CORE_MODULO (NOMBRE,DESCRIPCION,ACTIVOENTRADA,ACTIVOSALIDA) VALUES ('AlmacenarFichero','AlmacenarFichero',1,1);
INSERT INTO CORE_MODULO (NOMBRE,DESCRIPCION,ACTIVOENTRADA,ACTIVOSALIDA) VALUES ('ValidarEsquema','ValidarEsquema',1,1);
INSERT INTO CORE_MODULO (NOMBRE,DESCRIPCION,ACTIVOENTRADA,ACTIVOSALIDA) VALUES ('AlmacenarFicheroPlain','AlmacenarFicheroPlain',1,1);

--------------------------------------------------------
--  Inserts for Table PBL_CONFIG
    -- Se deben modificar pas propiedades de tipo DATABASE segon las necesidades
--------------------------------------------------------
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.xsd.base.path',                                                                            '/app/caib/pinbal/xsd',                                                                                                                                                                                    'propietat.xsd.base.path',                                                                                  'GENERAL',          0,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.optimitzar.transaccions.nova.consulta',                                                    'true',                                                                                                                                                                                                    'propietat.optimitzar.transaccions.nova.consulta',                                                          'GENERAL',          1,  'DATABASE', 'BOOL');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.entitat.accio.esborrar.activa',                                                            'true',                                                                                                                                                                                                    'propietat.entitat.accio.esborrar.activa',                                                                  'OPCIONS_BORRAR',   0,  'DATABASE', 'BOOL');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.procediment.accio.esborrar.activa',                                                        'true',                                                                                                                                                                                                    'propietat.procediment.accio.esborrar.activa',                                                              'OPCIONS_BORRAR',   1,  'DATABASE', 'BOOL');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.justificant.extensio.sortida',                                                             'pdf',                                                                                                                                                                                                     'propietat.justificant.extensio.sortida',                                                                   'JUSTIFICANT',      0,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.justificant.signar.i.custodiar',                                                           'true',                                                                                                                                                                                                    'propietat.justificant.signar.i.custodiar',                                                                 'JUSTIFICANT',      1,  'DATABASE', 'BOOL');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.justificant.convertir.pdfa',                                                               'true',                                                                                                                                                                                                    'propietat.justificant.convertir.pdfa',                                                                     'JUSTIFICANT',      2,  'DATABASE', 'BOOL');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.justificant.recobriment.generar',                                                          'false',                                                                                                                                                                                                   'propietat.justificant.recobriment.generar',                                                                'JUSTIFICANT',      3,  'DATABASE', 'BOOL');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.conversio.tipus',                                                                          'xdocreport',                                                                                                                                                                                              'propietat.conversio.tipus',                                                                                'CONVERSIO',        0,  'DATABASE', 'CONVERSIO_TIPUS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.conversio.open.office.host',                                                               'sdesooflin1.caib.es',                                                                                                                                                                                     'propietat.conversio.open.office.host',                                                                     'CONVERSIO',        1,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.conversio.open.office.port',                                                               '8100',                                                                                                                                                                                                    'propietat.conversio.open.office.port',                                                                     'CONVERSIO',        2,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.mapeig.rol.PBL_ADMIN',                                                                     'ROLE_ADMIN',                                                                                                                                                                                              'propietat.mapeig.rol.PBL_ADMIN',                                                                           'MAPEIG',           0,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.mapeig.rol.PBL_REPRES',                                                                    'ROLE_REPRES',                                                                                                                                                                                             'propietat.mapeig.rol.PBL_REPRES',                                                                          'MAPEIG',           1,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.mapeig.rol.PBL_DELEG',                                                                     'ROLE_DELEG',                                                                                                                                                                                              'propietat.mapeig.rol.PBL_DELEG',                                                                           'MAPEIG',           2,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.mapeig.rol.PBL_AUDIT',                                                                     'ROLE_AUDIT',                                                                                                                                                                                              'propietat.mapeig.rol.PBL_AUDIT',                                                                           'MAPEIG',           3,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.mapeig.rol.PBL_SUPERAUD',                                                                  'ROLE_SUPERAUD',                                                                                                                                                                                           'propietat.mapeig.rol.PBL_SUPERAUD',                                                                        'MAPEIG',           4,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.mapeig.rol.PBL_WS',                                                                        'ROLE_WS',                                                                                                                                                                                                 'propietat.mapeig.rol.PBL_WS',                                                                              'MAPEIG',           5,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.mapeig.rol.tothom',                                                                        'ROLE_DELEG',                                                                                                                                                                                              'propietat.mapeig.rol.tothom',                                                                              'MAPEIG',           6,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.recobriment.base.url',                                                                     'http://spreapplin1.caib.es:18080/pinbalrec',                                                                                                                                                              'propietat.recobriment.base.url',                                                                           'RECOBRIMENT',      0,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.recobriment.datos.especificos.processar',                                                  'true',                                                                                                                                                                                                    'propietat.recobriment.datos.especificos.processar',                                                        'RECOBRIMENT',      1,  'DATABASE', 'BOOL');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.recobriment.datos.especificos.incloure.ns',                                                'false',                                                                                                                                                                                                   'propietat.recobriment.datos.especificos.incloure.ns',                                                      'RECOBRIMENT',      2,  'DATABASE', 'BOOL');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.email.remitent',                                                                           'pinbal@limit.es',                                                                                                                                                                                         'propietat.email.remitent',                                                                                 'EMAIL',            0,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.email.footer',                                                                             'PINBAL Dev - Govern de les Illes Balears',                                                                                                                                                                'propietat.email.footer',                                                                                   'EMAIL',            1,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.dades.usuari.class',                                                                'es.caib.pinbal.plugins.caib.DadesUsuariPluginJdbc',                                                                                                                                                       'propietat.plugin.dades.usuari.class',                                                                      'USUARIS',          0,  'DATABASE', 'USUARIS_CLASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.dades.usuari.jdbc.datasource.jndi.name',                                            'java:es.caib.seycon.db.wl',                                                                                                                                                                               'propietat.plugin.dades.usuari.jdbc.datasource.jndi.name',                                                  'USUARIS',          1,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.dades.usuari.jdbc.query.codi',                                                      'select usu_codi, usu_nom, usu_nif, usu_codi | |''@caib.es'' from sc_wl_usuari where usu_codi = :codi',                                                                                                    'propietat.plugin.dades.usuari.jdbc.query.codi',                                                            'USUARIS',          2,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.dades.usuari.jdbc.query.nif',                                                       'select usu_codi, usu_nom, usu_nif, usu_codi || ''@caib.es'' from sc_wl_usuari where usu_nif = :nif',                                                                                                      'propietat.plugin.dades.usuari.jdbc.query.nif',                                                             'USUARIS',          3,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.dades.usuari.jdbc.query.rols',                                                      'select ugr_codgru from sc_wl_usugru where ugr_codusu=:codi',                                                                                                                                              'propietat.plugin.dades.usuari.jdbc.query.rols',                                                            'USUARIS',          4,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.dades.usuari.jdbc.query.grup',                                                      'select usu_codi, usu_nom, usu_nif, usu_codi||''@caib.es'' from sc_wl_usuari u, sc_wl_usugru g where g.ugr_codgru=:grup and g.ugr_codusu=u.usu_cod',                                                       'propietat.plugin.dades.usuari.jdbc.query.grup',                                                            'USUARIS',          5,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.dades.usuari.jdbc.query.any',                                                       'select usu_codi, usu_nom, usu_nif, usu_codi||''@caib.es'' from sc_wl_usuari where usu_codi like ''%'' || :text || ''%'' or usu_nif like ''%'' || :text || ''%'' or usu_nom like ''%'' || :text || ''%''', 'propietat.plugin.dades.usuari.jdbc.query.any',                                                             'USUARIS',          6,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.signatura.class',                                                                   'es.caib.pinbal.plugins.caib.SignaturaPluginCaib',                                                                                                                                                         'propietat.plugin.signatura.class',                                                                         'SIGNATURA',        0,  'DATABASE', 'SIGNATURA_CLASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.signatura.caib.certificat.alias',                                                   'CERTIFICAT DE DEV DE LA DGMAD',                                                                                                                                                                           'propietat.plugin.signatura.caib.certificat.alias',                                                         'SIGNATURA',        1,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.signatura.caib.certificat.password',                                                '********',                                                                                                                                                                                                'propietat.plugin.signatura.caib.certificat.password',                                                      'SIGNATURA',        2,  'FILE',     'PASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.signatura.caib.content.type',                                                       null,                                                                                                                                                                                                      'propietat.plugin.signatura.caib.content.type',                                                             'SIGNATURA',        3,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.class',                                                               'es.caib.pinbal.plugins.caib.FirmaSimpleServidorPluginPortafib',                                                                                                                                           'propietat.plugin.firmaservidor.class',                                                                     'FIRMA_SERVIDOR',   0,  'DATABASE', 'FIRMA_SERVIDOR_CLASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.portafib.plugins.signatureserver.portafib.api_passarela_url',         'https://proves.caib.es/portafib/ws/v1/PortaFIBPassarelaDeFirmaEnServidor',                                                                                                                                'propietat.plugin.firmaservidor.portafib.plugins.signatureserver.portafib.api_passarela_url',               'FIRMA_SERVIDOR',   1,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.portafib.plugins.signatureserver.portafib.api_passarela_username',    '$pinbal_portafib_pre',                                                                                                                                                                                    'propietat.tasca.plugin.firmaservidor.portafib.plugins.signatureserver.portafib.api_passarela_username',    'FIRMA_SERVIDOR',   2,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.portafib.plugins.signatureserver.portafib.api_passarela_password',    '********',                                                                                                                                                                                                'propietat.plugin.firmaservidor.portafib.plugins.signatureserver.portafib.api_passarela_password',          'FIRMA_SERVIDOR',   3,  'FILE',     'PASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.portafib.username',                                                   'preprod-dgmad',                                                                                                                                                                                           'propietat.plugin.firmaservidor.portafib.username',                                                         'FIRMA_SERVIDOR',   4,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.portafib.location',                                                   'Palma',                                                                                                                                                                                                   'propietat.plugin.firmaservidor.portafib.location',                                                         'FIRMA_SERVIDOR',   5,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.portafib.signerEmail',                                                'suport@caib.es',                                                                                                                                                                                          'propietat.plugin.firmaservidor.portafib.signerEmail',                                                      'FIRMA_SERVIDOR',   6,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.portafib.endpoint',                                                   'https://proves.caib.es/portafib/common/rest/apifirmaenservidorsimple/v1/',                                                                                                                                'propietat.plugin.firmaservidor.portafib.endpoint',                                                         'FIRMA_SERVIDOR',   7,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.portafib.auth.username',                                              '$pinbal_portafib_pre',                                                                                                                                                                                    'propietat.plugin.firmaservidor.portafib.auth.username',                                                    'FIRMA_SERVIDOR',   8,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.portafib.auth.password',                                              '********',                                                                                                                                                                                                'propietat.plugin.firmaservidor.portafib.auth.password',                                                    'FIRMA_SERVIDOR',   9,  'FILE',     'PASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.firmaservidor.portafib.perfil',                                                     'PADES',                                                                                                                                                                                                   'propietat.plugin.firmaservidor.portafib.perfil',                                                           'FIRMA_SERVIDOR',   10, 'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.custodia.class',                                                                    'es.caib.pinbal.plugins.caib.CustodiaPluginCaib',                                                                                                                                                          'propietat.plugin.custodia.class',                                                                          'CUSTODIA',         0,  'DATABASE', 'CUSTODIA_CLASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.custodia.caib.url',                                                                 'https://proves.caib.es/signatura/services/CustodiaDocumentos',                                                                                                                                            'propietat.plugin.custodia.caib.url',                                                                       'CUSTODIA',         1,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.custodia.caib.username',                                                            'PINBAL',                                                                                                                                                                                                  'propietat.plugin.custodia.caib.username',                                                                  'CUSTODIA',         2,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.custodia.caib.password',                                                            '********',                                                                                                                                                                                                'propietat.plugin.custodia.caib.password',                                                                  'CUSTODIA',         3,  'FILE',     'PASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.custodia.caib.tipus.document',                                                      'PBL_JUSTIFICANT_VERIFICACIO_DADES',                                                                                                                                                                       'propietat.plugin.custodia.caib.tipus.document',                                                            'CUSTODIA',         4,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.custodia.caib.verificacio.url.base',                                                 null,                                                                                                                                                                                                      'propietat.plugin.custodia.caib.verificacio.url.bas',                                                       'CUSTODIA',         5,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.class',                                                                       'es.caib.plugins.arxiu.caib.ArxiuPluginCaib',                                                                                                                                                              'propietat.plugin.arxiu.class',                                                                             'ARXIU',            0,  'DATABASE', 'ARXIU_CLASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.caib.base.url',                                                               'https://esbse.caib.es:4430/esb',                                                                                                                                                                          'propietat.plugin.arxiu.caib.base.url',                                                                     'ARXIU',            1,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.caib.aplicacio.codi',                                                         'PINBAL',                                                                                                                                                                                                  'propietat.plugin.arxiu.caib.aplicacio.codi',                                                               'ARXIU',            2,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.caib.usuari',                                                                 'pinbal',                                                                                                                                                                                                  'propietat.plugin.arxiu.caib.usuari',                                                                       'ARXIU',            3,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.caib.contrasenya',                                                            '********',                                                                                                                                                                                                'propietat.plugin.arxiu.caib.contrasenya',                                                                  'ARXIU',            4,  'FILE',     'PASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.caib.csv_generation_definition',                                              'CSV_DEF',                                                                                                                                                                                                 'propietat.plugin.arxiu.caib.csv_generation_definition',                                                    'ARXIU',            5,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.caib.conversio.imprimible.url',                                               'https://se.caib.es/concsvapi/interna/printable/uuid',                                                                                                                                                     'propietat.plugin.arxiu.caib.conversio.imprimible.url',                                                     'ARXIU',            6,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.caib.conversio.imprimible.usuari',                                            '$pinbal_concsv',                                                                                                                                                                                          'propietat.tasca.plugin.arxiu.caib.conversio.imprimible.usuari',                                            'ARXIU',            7,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.caib.conversio.imprimible.contrasenya',                                       '********',                                                                                                                                                                                                'propietat.plugin.arxiu.caib.conversio.imprimible.contrasenya',                                             'ARXIU',            8,  'FILE',     'PASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.caib.timeout.connect',                                                        '20000',                                                                                                                                                                                                   'propietat.plugin.arxiu.caib.timeout.connect',                                                              'ARXIU',            9,  'DATABASE', 'INT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.caib.timeout.read',                                                           '20000',                                                                                                                                                                                                   'propietat.plugin.arxiu.caib.timeout.read',                                                                 'ARXIU',            10, 'DATABASE', 'INT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.arxiu.serie.documental',                                                            'SPINBAL',                                                                                                                                                                                                 'propietat.plugin.arxiu.serie.documental',                                                                  'ARXIU',            11, 'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.unitats.organitzatives.class',                                                      'es.caib.pinbal.plugin.caib.unitat.UnitatsOrganitzativesPluginDir3',                                                                                                                                       'propietat.plugin.unitats.organitzatives.class',                                                            'UNITATS',          0,  'DATABASE', 'UNITATS_CLASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.unitats.organitzatives.dir3.service.url',                                           'http://dev.caib.es/dir3caib',                                                                                                                                                                             'propietat.plugin.unitats.organitzatives.dir3.service.url',                                                 'UNITATS',          1,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.unitats.organitzatives.dir3.service.username',                                      '$pinbal_dir3caib',                                                                                                                                                                                        'propietat.plugin.unitats.organitzatives.dir3.service.username',                                            'UNITATS',          2,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.unitats.organitzatives.dir3.service.password',                                      '********',                                                                                                                                                                                                'propietat.plugin.unitats.organitzatives.dir3.service.password',                                            'UNITATS',          3,  'FILE',     'PASS');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.unitats.organitzatives.dir3.service.log.actiu',                                     'true',                                                                                                                                                                                                    'propietat.plugin.unitats.organitzatives.dir3.service.log.actiu',                                           'UNITATS',          4,  'DATABASE', 'BOOL');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.plugin.unitats.cerca.dir3.service.url',                                                    'https://dev.caib.es/dir3caib/rest/busqueda/organismos',                                                                                                                                                   'propietat.plugin.unitats.cerca.dir3.service.url',                                                          'UNITATS',          5,  'FILE',     'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.tasca.auto.arxivar.consultes.cron',                                                        '0 0 1 * * ?',                                                                                                                                                                                             'propietat.tasca.auto.arxivar.consultes.cron',                                                              'HISTORIC',         0,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.tasca.auto.arxivar.antiguetat.dies',                                                       '180',                                                                                                                                                                                                     'propietat.tasca.auto.arxivar.antiguetat.dies',                                                             'HISTORIC',         1,  'DATABASE', 'INT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.tasca.auto.comprovacio.repeticio',                                                         '10000',                                                                                                                                                                                                   'propietat.tasca.auto.comprovacio.repeticio',                                                               'TASQUES',          0,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.tasca.auto.justificant.repeticio',                                                         null,                                                                                                                                                                                                      'propietat.tasca.auto.justificant.repeticio',                                                               'TASQUES',          1,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.tasca.auto.exp.tancar.cron',                                                               null,                                                                                                                                                                                                      'propietat.tasca.auto.exp.tancar.cron',                                                                     'TASQUES',          2,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.tasca.auto.email.report.estat.cron',                                                       '0 0 22 * * *',                                                                                                                                                                                            'propietat.tasca.auto.email.report.estat.cron',                                                             'TASQUES',          3,  'DATABASE', 'TEXT');
INSERT INTO PBL_CONFIG (KEY, VALUE, DESCRIPTION_KEY, GROUP_CODE, POSITION, SOURCE_PROPERTY, TYPE_CODE) VALUES ('es.caib.pinbal.tasca.auto.generar.explotacio.cron',                                                       '0 30 0 * * ?',                                                                                                                                                                                            'propietat.tasca.auto.generar.explotacio.cron',                                                             'TASQUES',          4,  'DATABASE', 'TEXT');


--------------------------------------------------------
--  Inserts for Table PBL_USUARI
--  Es dóna d'alta l'usuari per a assignar-lo com a creador dels inserts de serveis i procediments
--------------------------------------------------------
INSERT INTO PBL_USUARI (CODI, NOM, NIF, EMAIL, IDIOMA, INICIALITZAT, VERSION, PROCEDIMENT_ID, SERVEI_CODI, ENTITAT_ID, DEPARTAMENT, FINALITAT, NUM_ELEMENTS_PAGINA) VALUES ('e18225486x', 'Melcior', '18225486X', 'e18225486x@caib.es', 'CA', 1, 0, null, null, null, null, null, 10);


--------------------------------------------------------
--  Inserts for Table PBL_ENTITAT
--------------------------------------------------------
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1, 'GOVERN', 'Govern de les Illes Balears', null, 'S0711001H', 1, 1, 'A04003003', 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 3);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1082, '7046', 'Sant Antoni de Portmany', NULL, 'P0704600F', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1083, '7050', 'Sant Joan de Labritja', NULL, 'P0705000H', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1084, '7902', 'Es Migjorn Gran ', NULL, 'P0700001A', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1085, '7901', 'Ariany   ', NULL, 'P0706600D', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1086, '7031', 'Llucmajor   ', NULL, 'P0703100H', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1087, '7041', 'Petraa   ', NULL, 'P0704100G', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 3);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1088, '7042', 'Pollença   ', NULL, 'P0704200E', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1089, '7043', 'Porreres   ', NULL, 'P0704300C', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1090, '7044', 'Sa Pobla  ', NULL, 'P0704400A', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1091, '7045', 'Puigpunyent   ', NULL, 'P0704500H', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1092, '7047', 'Sencelles   ', NULL, 'P0704700D', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1093, '7048', 'Sant Josep de sa Talaia', NULL, 'P0704800B', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1094, '7049', 'Sant Joan  ', NULL, 'P0704900J', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1095, '7051', 'Sant Llorenç des Cardassar', NULL, 'P0705100F', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1096, '7052', 'Sant Lluís  ', NULL, 'P0705200D', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1097, '7053', 'Santa Eugènia  ', NULL, 'P0705300B', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1098, '7054', 'Santa Eulalia del Río', NULL, 'P0705400J', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1099, '7055', 'Santa Margalida  ', NULL, 'P0705500G', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1100, '7056', 'Santa María del Camí', NULL, 'P0705600E', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1101, '7057', 'Santanyí   ', NULL, 'P0705700C', 3, 0, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 1);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1102, '7058', 'Selva   ', NULL, 'P0705800A', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1103, '7059', 'Ses Salines  ', NULL, 'P0705900I', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1104, '7060', 'Sineo   ', NULL, 'P0706000G', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 1);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1105, '7061', 'Sóller   ', NULL, 'P0706100E', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1106, '7062', 'Son Servera  ', NULL, 'P0706200C', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1107, '7063', 'Valldemossa   ', NULL, 'P0706300A', 3, 0, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 3);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1108, '7064', 'Es Castell  ', NULL, 'P0706400I', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1109, '7065', 'Vilafranca de Bonany1 ', NULL, 'P0706500F', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 5);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1110, '7003', 'Alcúdia   ', NULL, 'P0700300G', 3, 1, 'aaaa', 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 1);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1111, '7004', 'Algaida   ', NULL, 'P0700400E', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1112, '7005', 'Andratx   ', NULL, 'P0700500B', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1113, '7006', 'Artà   ', NULL, 'P0700600J', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1114, '7007', 'Banyalbufar   ', NULL, 'P0700700H', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1115, '7008', 'Binissalem   ', NULL, 'P0700800F', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1116, '7009', 'Búger   ', NULL, 'P0700900D', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1117, '7010', 'Bunyola   ', NULL, 'P0701000B', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1118, '7011', 'Calvià   ', NULL, 'P0701100J', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1119, '7012', 'Campanet   ', NULL, 'P0701200H', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1120, '7013', 'Campos   ', NULL, 'P0701300F', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1121, '7014', 'Capdepera   ', NULL, 'P0701400D', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1122, '7015', 'Ciutadella de Menorca ', NULL, 'P0701500A', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1123, '7016', 'Consell   ', NULL, 'P0701600I', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1124, '7017', 'Costitx   ', NULL, 'P0701700G', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1125, '7018', 'Deyá   ', NULL, 'P0701800E', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1126, '7019', 'Escorca   ', NULL, 'P0701900C', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1127, '7020', 'Esporles   ', NULL, 'P0702000A', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1128, '7021', 'Estellencs   ', NULL, 'P0702100I', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1129, '7022', 'Felanitx   ', NULL, 'P0702200G', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1130, '7023', 'Ferreries   ', NULL, 'P0702300E', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1131, '7024', 'Formentera   ', NULL, 'P0702400C', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1132, '7025', 'Fornalutx   ', NULL, 'P0702500J', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1133, '7026', 'Eivissa   ', NULL, 'P0702600H', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1134, '7027', 'Inca   ', NULL, 'P0702700F', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1135, '7028', 'Lloret de Vistalegre ', NULL, 'P0702800D', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1136, '7029', 'Lloseta   ', NULL, 'P0702900B', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1137, '7030', 'Llubí   ', NULL, 'P0703000J', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1138, '7032', 'Maó   ', NULL, 'P0703200F', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1139, '7033', 'Manacor   ', NULL, 'P0703300D', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1140, '7034', 'Mancor de la Vall', NULL, 'P0703400B', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1141, '7035', 'Maria de la Salut', NULL, 'P0703500I', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1142, '7036', 'Marratxí   ', NULL, 'P0703600G', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1143, '7037', 'Es Mercadal  ', NULL, 'P0703700E', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1144, '7038', 'Montuïri   ', NULL, 'P0703800C', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (1145, '7039', 'Muro   ', NULL, 'P0703900A', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (8426, 'UIB', 'Universitat de les Illes Balears', NULL, 'Q0718001A', 0, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (107, 'BIT', 'Fundació BIT  ', NULL, 'G57775884', 0, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 3);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (383399, 'IBSALUT', 'Servei de Salut de les Illes Balears', NULL, 'Q0719003F', 1, 1, 'A04003754', 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (8645, '99999999', 'Prova entitat  1', NULL, '12345678Z', 0, 1, 'asdfas', 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 3);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (702, '7040', 'Ajuntament de Palma ', NULL, 'G07896004', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 1);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (2507, '7001', 'Alaró   ', NULL, 'P0706300A', 3, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (20366, 'CIMA', 'Consell de Mallorca ', NULL, 'S0711002F', 2, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (10910, 'IMAS', 'Institut Mallorquí d''Afers Socials', NULL, 'Q0700448D', 0, 1, NULL, 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (289605, 'ATIB', 'Agència Tributària de les Illes Balears', NULL, 'Q0700546E', 0, 1, 'A04013587', 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 2);
INSERT INTO PBL_ENTITAT (ID, CODI, NOM, RESPONSABLE, CIF, TIPUS, ACTIVA, UNITAT_ARREL, CREATEDBY_CODI, CREATEDDATE, LASTMODIFIEDBY_CODI, LASTMODIFIEDDATE, VERSION) VALUES (422054, 'LA0004547', 'Consorci Serra de Tramuntana Patrimoni Mundial', NULL, 'P0700056E', 0, 1, 'LA0004547', 'e18225486x', SYSDATE, 'e18225486x', SYSDATE, 0);
