changeLogFile=db/changelog/db.changelog-master.yaml
url=offline:oracle?changeLogFile=liquibase/databasechangelog.csv
#url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
username=pinbal2
password=pinbal2
driver=oracle.jdbc.driver.OracleDriver
outputChangeLogFile=liquibase/liquibase-changelog.yaml
defaultSchemaName=PINBAL
liquibaseSchemaName=PINBAL
