<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 sp1 (http://www.altova.com) by End User (free.org) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" targetNamespace="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="DatosEspecificos">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="Consulta"/>
				<xs:element ref="Retorno"/>
			</xs:choice>
			<xs:attribute name="Id" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Consulta">
		<xs:annotation>
			<xs:documentation>Datos de consulta para servicio de obtención de centros universitarios</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="FechaDesde"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="Retorno">
		<xs:annotation>
			<xs:documentation>Datos de retorno para servicio de obtención de centros universitarios</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Estado"/>
				<xs:element ref="Universidades" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CodigoCentro">
		<xs:annotation>
			<xs:documentation>Código RUCT del centro</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:whiteSpace value="collapse"/>
				<xs:pattern value="\d{8}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FechaDesde">
		<xs:annotation>
			<xs:documentation>Fecha desde la que se obtendrán las modificaciones de los centros</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:date"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Estado">
		<xs:complexType>
			<xs:all>
				<xs:element name="CodigoEstado">
					<xs:annotation>
						<xs:documentation>Codigo de estado</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="4"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Literal">
					<xs:annotation>
						<xs:documentation>Descripcion del estado</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="1024"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="Universidades">
		<xs:annotation>
			<xs:documentation>Lista de universidades obtenidos</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Universidad" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Universidad">
		<xs:annotation>
			<xs:documentation>Datos de la universidad obtenida</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="CodigoUniversidad"/>
				<xs:element name="Universidad">
					<xs:annotation>
						<xs:documentation>Universidad a la que pertenece el centro obtenido</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="75"/>
							<xs:whiteSpace value="collapse"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element ref="NombreCorto"/>
				<xs:element ref="Acronimo" minOccurs="0"/>
				<xs:element ref="NIF" minOccurs="0"/>
				<xs:element ref="TipoUniversidad"/>
				<xs:element ref="Naturaleza"/>
				<xs:element ref="Situacion"/>
				<xs:element ref="CodigoPais"/>
				<xs:element ref="CodigoComunidadAutonoma"/>
				<xs:element ref="CodigoProvincia" minOccurs="0"/>
				<xs:element ref="Provincia" minOccurs="0"/>
				<xs:element ref="CodigoMunicipio" minOccurs="0"/>
				<xs:element ref="CodigoLocalidad" minOccurs="0"/>
				<xs:element ref="Localidad" minOccurs="0"/>
				<xs:element ref="Direccion" minOccurs="0"/>
				<xs:element ref="CodigoPostal" minOccurs="0"/>
				<xs:element ref="Telefono" minOccurs="0"/>
				<xs:element ref="TelefonoSecundario" minOccurs="0"/>
				<xs:element ref="Fax" minOccurs="0"/>
				<xs:element ref="Email" minOccurs="0"/>
				<xs:element ref="URLWeb" minOccurs="0"/>
				<xs:element ref="PerteneceIglesia" minOccurs="0"/>
				<xs:element ref="CodigoErasmus" minOccurs="0"/>
				<xs:element ref="AnimoLucro" minOccurs="0"/>
				<xs:element ref="FechaVigor" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="NombreCorto">
		<xs:annotation>
			<xs:documentation>Nombre corto de la universidad</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="50"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="NIF">
		<xs:annotation>
			<xs:documentation>NIF de la universidad obtenida</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:length value="9"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="TipoUniversidad">
		<xs:annotation>
			<xs:documentation>Tipo de universidad</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="U000"/>
				<xs:enumeration value="U001"/>
				<xs:enumeration value="U002"/>
				<xs:enumeration value="U003"/>
				<xs:enumeration value="U004"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoPais">
		<xs:annotation>
			<xs:documentation>Código del país al que pertenece la universidad</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{3}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoMunicipio">
		<xs:annotation>
			<xs:documentation>Código del municipio al que pertenece la universidad</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="50"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Acronimo">
		<xs:annotation>
			<xs:documentation>Acrónimo de la universidad</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="10"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Situacion">
		<xs:annotation>
			<xs:documentation>Situacion de la universidad</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="A"/>
				<xs:enumeration value="B"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Naturaleza">
		<xs:annotation>
			<xs:documentation>Naturaleza de la universidad</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="1"/>
				<xs:enumeration value="2"/>
				<xs:enumeration value="3"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Direccion">
		<xs:annotation>
			<xs:documentation>Dirección de la universidad</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="100"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoComunidadAutonoma">
		<xs:annotation>
			<xs:documentation>Código de comunidad autónoma de la universidad</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="01"/>
				<xs:enumeration value="02"/>
				<xs:enumeration value="03"/>
				<xs:enumeration value="04"/>
				<xs:enumeration value="05"/>
				<xs:enumeration value="06"/>
				<xs:enumeration value="07"/>
				<xs:enumeration value="08"/>
				<xs:enumeration value="09"/>
				<xs:enumeration value="10"/>
				<xs:enumeration value="11"/>
				<xs:enumeration value="12"/>
				<xs:enumeration value="13"/>
				<xs:enumeration value="14"/>
				<xs:enumeration value="15"/>
				<xs:enumeration value="16"/>
				<xs:enumeration value="17"/>
				<xs:enumeration value="18"/>
				<xs:enumeration value="19"/>
				<xs:enumeration value="00"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoProvincia">
		<xs:annotation>
			<xs:documentation>Código de provincia de la universidad</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{2}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Provincia">
		<xs:annotation>
			<xs:documentation>Provincia de la universidad</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="25"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoLocalidad">
		<xs:annotation>
			<xs:documentation>Código de localidad de la universidad</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{9}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Localidad">
		<xs:annotation>
			<xs:documentation>Localidad de la universidad</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="70"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoUniversidad">
		<xs:annotation>
			<xs:documentation>Código de la universidad</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{3}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Telefono">
		<xs:annotation>
			<xs:documentation>Telefono secundario de la universidad obtenida</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="9"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="TelefonoSecundario">
		<xs:annotation>
			<xs:documentation>Telefono secundario de la universidad obtenida</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="9"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Email">
		<xs:annotation>
			<xs:documentation>Email de la universidad obtenida</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="50"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Fax">
		<xs:annotation>
			<xs:documentation>Fax de la universidad</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="9"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="URLWeb">
		<xs:annotation>
			<xs:documentation>Url de la web de la universidad obtenida</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="75"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoPostal">
		<xs:annotation>
			<xs:documentation>Código postal de la universidad</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:int">
				<xs:pattern value="\d{5}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="PerteneceIglesia">
		<xs:annotation>
			<xs:documentation>Indica si la universidad pertenece a la iglesia</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="S"/>
				<xs:enumeration value="N"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoErasmus">
		<xs:annotation>
			<xs:documentation>Indica el código de erasmus de la universidad</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="15"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="AnimoLucro">
		<xs:annotation>
			<xs:documentation>Indica si la universidad tiene ánimo de lucro</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="S"/>
				<xs:enumeration value="N"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FechaVigor">
		<xs:annotation>
			<xs:documentation>Fecha de entrada en vigor de la universidad</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:date"/>
		</xs:simpleType>
	</xs:element>
</xs:schema>
