<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>es.caib.pinbal</groupId>
	<artifactId>pinbal</artifactId>
	<version>2.0.1</version>
	<packaging>pom</packaging>
	<url>https://github.com/GovernIB/pinbal</url>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.7.18</version>
		<relativePath />
	</parent>
	<properties>
		<axis2.version>1.6.4</axis2.version>
		<poi.version>5.5.1</poi.version>
		<axiom.version>1.2.15</axiom.version>
		<rampart.version>1.6.4</rampart.version>
		<firma.simple.version>1.0.3</firma.simple.version>
		<dir3caib.version>1.1.1</dir3caib.version>
		<usuaris.ldap.version>4.0.0-SNAPSHOT</usuaris.ldap.version>
		<spring.version>${spring-framework.version}</spring.version>
		<spring-data-jpa.version>2.7.12</spring-data-jpa.version>
		<hibernate.validator.version>${hibernate-validator.version}</hibernate.validator.version>
		<orika.version>1.5.4</orika.version>
		<lombok.version>1.18.46</lombok.version>
		<spring-boot.version>2.7.12</spring-boot.version>
		<keycloak.version>21.1.1</keycloak.version>
		<orika.starter.version>2.4.6</orika.starter.version>
		<scsp.core.version>5.0.11</scsp.core.version>
		<scsp.beans.version>5.0.11</scsp.beans.version>
		<scsp.rampart.core.version>1.6.4.1</scsp.rampart.core.version>
		<mapstruct.version>1.5.5.Final</mapstruct.version>
		<jackson.version>2.14.1</jackson.version>
		<cxf.version>3.2.12.redhat-00001</cxf.version>
		<wss4j.version>2.2.5.redhat-00002</wss4j.version>
		<jodconverter.version>4.4.11</jodconverter.version>
		<xdocreport.version>2.0.6</xdocreport.version>
		<arxiu.api.version>2.0.27</arxiu.api.version>
		<pluginsib.arxiu.version>${arxiu.api.version}</pluginsib.arxiu.version>
		<comanda.api.version>1.0.0</comanda.api.version>
		<junit.jupiter.version>5.9.3</junit.jupiter.version>
		<java.compiler.version>11</java.compiler.version>
		<maven.compiler.target>${java.compiler.version}</maven.compiler.target>
		<maven.compiler.source>${java.compiler.version}</maven.compiler.source>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<build.timestamp>${maven.build.timestamp}</build.timestamp>
		<implementation.vendor>Límit Tecnologies</implementation.vendor>
		<version.full>${project.version}</version.full>
	</properties>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springdoc</groupId>
				<artifactId>springdoc-openapi-ui</artifactId>
				<version>1.8.0</version>
			</dependency>
			<dependency>
				<groupId>org.springdoc</groupId>
				<artifactId>springdoc-openapi-hateoas</artifactId>
				<version>1.8.0</version>
			</dependency>
			<dependency>
				<groupId>org.springdoc</groupId>
				<artifactId>springdoc-openapi-security</artifactId>
				<version>1.8.0</version>
			</dependency>
			<dependency>
				<groupId>com.turkraft</groupId>
				<artifactId>spring-filter</artifactId>
				<version>2.1.6</version>
			</dependency>
			<dependency>
				<groupId>net.sf.jasperreports</groupId>
				<artifactId>jasperreports</artifactId>
				<version>6.21.4</version>
			</dependency>
			<dependency>
				<groupId>net.sourceforge.dynamicreports</groupId>
				<artifactId>dynamicreports-core</artifactId>
				<version>6.12.1</version>
			</dependency>
			<dependency>
				<groupId>org.keycloak.bom</groupId>
				<artifactId>keycloak-adapter-bom</artifactId>
				<version>${keycloak.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>opensymphony</groupId>
				<artifactId>sitemesh</artifactId>
				<version>2.5.0</version>
			</dependency>
			<dependency>
				<groupId>javax.ejb</groupId>
				<artifactId>javax.ejb-api</artifactId>
				<version>3.2.2</version>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-collections4</artifactId>
				<version>4.4</version>
			</dependency>
			<dependency>
				<groupId>commons-beanutils</groupId>
				<artifactId>commons-beanutils</artifactId>
				<version>1.9.4</version>
			</dependency>
			<dependency>
				<groupId>commons-io</groupId>
				<artifactId>commons-io</artifactId>
				<version>2.16.1</version>
			</dependency>
			<dependency>
				<groupId>commons-fileupload</groupId>
				<artifactId>commons-fileupload</artifactId>
				<version>1.6.0</version>
			</dependency>
<!--			<dependency>-->
<!--				<groupId>com.google.guava</groupId>-->
<!--				<artifactId>guava</artifactId>-->
<!--				<version>30.1.1-jre</version>-->
<!--			</dependency>-->
			<dependency>
				<groupId>org.jboss.bom</groupId>
				<artifactId>jboss-eap-javaee8</artifactId>
				<version>7.2.9.GA</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>javax.ws.rs</groupId>
				<artifactId>jsr311-api</artifactId>
				<version>1.1.1</version>
				<scope>provided</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<modules>
		<module>pinbal-back</module>
		<module>pinbal-backend</module>
		<module>pinbal-api-interna</module>
		<module>pinbal-api-externa</module>
		<module>pinbal-service-intf</module>
		<module>pinbal-service</module>
		<module>pinbal-persistence</module>
		<module>pinbal-plugin-intf</module>
		<module>pinbal-plugin</module>
		<module>pinbal-scsp</module>
		<module>pinbal-ejb</module>
		<module>pinbal-ear</module>
		<module>pinbal-client</module>
		<module>pinbal-client-legacy</module>
		<module>pinbal-client-intf</module>
	</modules>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-deploy-plugin</artifactId>
				<version>3.1.4</version>
				<configuration>
					<altDeploymentRepository>internal.repo::default::file://${project.build.directory}/mvn-repo</altDeploymentRepository>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.github.github</groupId>
				<artifactId>site-maven-plugin</artifactId>
				<version>0.12</version>
				<configuration>
					<message>Maven artifacts for ${project.version}</message>
					<outputDirectory>${project.build.directory}/mvn-repo</outputDirectory>
					<noJekyll>true</noJekyll>
					<branch>refs/heads/gh-pages</branch>
					<includes>
						<include>**/*</include>
					</includes>
					<path>maven</path>
					<repositoryName>maven</repositoryName>
					<repositoryOwner>GovernIB</repositoryOwner>
					<server>github_governib_maven</server>
					<merge>true</merge>
					<dryRun>false</dryRun>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>site</goal>
						</goals>
						<phase>deploy</phase>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>versions-maven-plugin</artifactId>
				<version>2.8.1</version>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>buildnumber-maven-plugin</artifactId>
				<version>3.2.1</version>
				<executions>
					<execution>
						<phase>validate</phase>
						<goals>
							<goal>create</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<doCheck>false</doCheck>
					<doUpdate>false</doUpdate>
					<ignoreEmptyScmUrl>true</ignoreEmptyScmUrl>
				</configuration>
			</plugin>
<!--			<plugin>-->
<!--				<groupId>io.github.git-commit-id</groupId>-->
<!--				<artifactId>git-commit-id-maven-plugin</artifactId>-->
<!--				<version>7.0.0</version>-->
<!--				<executions>-->
<!--					<execution>-->
<!--						<id>get-the-git-infos</id>-->
<!--						<goals>-->
<!--							<goal>revision</goal>-->
<!--						</goals>-->
<!--					</execution>-->
<!--				</executions>-->
<!--				<configuration>-->
<!--					<generateGitPropertiesFile>true</generateGitPropertiesFile>-->
<!--					<generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>-->
<!--					<includeOnlyProperties>-->
<!--						<includeOnlyProperty>git.commit.id</includeOnlyProperty>-->
<!--						<includeOnlyProperty>git.build.time</includeOnlyProperty>-->
<!--						<includeOnlyProperty>git.build.version</includeOnlyProperty>-->
<!--					</includeOnlyProperties>-->
<!--				</configuration>-->
<!--			</plugin>-->
		</plugins>
	</build>
	<distributionManagement>
		<repository>
			<id>github_governib_maven</id>
			<name>GitHub GovernIB Maven Repository</name>
			<url>file://${project.build.directory}/mvn-repo</url>
		</repository>
	</distributionManagement>
	<repositories>
		<repository>
			<id>redhatGA</id>
			<url>https://maven.repository.redhat.com/ga/</url>
		</repository>
	</repositories>
</project>
