<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" targetNamespace="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="DatosEspecificos" type="DatosEspecificos"/>
	<xs:complexType name="DatosEspecificos">
		<xs:choice>
			<xs:element ref="Consulta"/>
			<xs:element ref="Retorno"/>
		</xs:choice>
		<xs:attribute name="Id" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:element name="Consulta">
		<xs:complexType>
			<xs:all>
				<xs:element ref="NumeroNacionalAsociacion" minOccurs="0"/>
				<xs:element ref="Denominacion" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="NumeroNacionalAsociacion">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{1,10}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Denominacion">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="300"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Retorno">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Estado"/>
				<xs:choice minOccurs="0">
					<xs:element ref="Asociacion"/>
					<xs:element ref="Asociaciones"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Estado">
		<xs:complexType>
			<xs:all>
				<xs:element ref="CodigoEstado"/>
				<xs:element ref="CodigoEstadoSecundario" minOccurs="0"/>
				<xs:element ref="LiteralError"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="CodigoEstado">
		<xs:annotation>
			<xs:documentation>Código de estado que devuelve la petición de consulta.</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="4"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoEstadoSecundario">
		<xs:annotation>
			<xs:documentation>Codigo de estado secundario de la transmisión</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="10"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="LiteralError">
		<xs:annotation>
			<xs:documentation>Mensaje retorno con la contestación a la consulta.</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="1024"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Asociacion">
		<xs:complexType>
			<xs:all>
				<xs:element ref="NumeroNacionalAsociacion"/>
				<xs:element ref="Denominacion"/>
				<xs:element ref="Actividad" minOccurs="0"/>
				<xs:element ref="Tipo"/>
				<xs:element ref="Situacion"/>
				<xs:element ref="Miembros" minOccurs="0"/>
				<xs:element name="FechaConstitucion" type="Fecha" minOccurs="0"/>
				<xs:element name="FechaInscripcion" type="Fecha" minOccurs="0"/>
				<xs:element name="FechaUtilidadPublica" type="Fecha" minOccurs="0"/>
				<xs:element ref="Localizacion" minOccurs="0"/>
				<xs:element ref="NotasMarginales" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="Asociaciones">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Asociacion" type="Asociacion" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Asociacion">
		<xs:all>
			<xs:element ref="NIF" minOccurs="0"/>
			<xs:element ref="NumeroNacionalAsociacion"/>
			<xs:element ref="Denominacion"/>
		</xs:all>
	</xs:complexType>
	<xs:element name="Actividad">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="150"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Tipo">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="150"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Situacion">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="150"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:simpleType name="Fecha">
		<xs:restriction base="xs:date"/>
	</xs:simpleType>
	<xs:element name="Miembros">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Miembro" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Miembro">
		<xs:complexType>
			<xs:all>
				<xs:element ref="Documentacion" minOccurs="0"/>
				<xs:element ref="Nombre" minOccurs="0"/>
				<xs:element ref="Cargo"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="Documentacion">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="30"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="NIF">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="9"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Nombre">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="150"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Cargo">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="100"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Localizacion">
		<xs:complexType>
			<xs:all>
				<xs:element ref="CodigoPostal" minOccurs="0"/>
				<xs:element ref="Provincia"/>
				<xs:element ref="Municipio"/>
				<xs:element ref="Domicilio"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="CodigoPostal">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{5}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Provincia">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="100"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Municipio">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="100"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Domicilio">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="250"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="NotasMarginales">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="NotaMarginal" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="NotaMarginal">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="5000"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>
