GRANT SELECT, UPDATE, INSERT, DELETE ON ACL_CLASS TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON ACL_ENTRY TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON ACL_OBJECT_IDENTITY TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON ACL_SID TO WWW_PINBAL;
GRANT SELECT ON ACL_SID_SEQ TO WWW_PINBAL;
GRANT SELECT ON ACL_CLASS_SEQ TO WWW_PINBAL;
GRANT SELECT ON ACL_OID_SEQ TO WWW_PINBAL;
GRANT SELECT ON ACL_ENTRY_SEQ TO WWW_PINBAL;

GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_BLOQUEO  TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_CACHE_CERTIFICADOS TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_CLAVE_PRIVADA TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_CLAVE_PUBLICA TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_EMISOR_CERTIFICADO TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_LOG TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_MODULO TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_MODULO_CONFIGURACION TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_PARAMETRO_CONFIGURACION TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_PETICION_RESPUESTA TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_SECUENCIA_IDPETICION TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_SERVICIO TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_TIPO_MENSAJE TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_TOKEN_DATA TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON CORE_TRANSMISION TO WWW_PINBAL;

GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_CONSULTA TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_ENTITAT TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_ENTITAT_SERVEI TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_ENTITAT_USUARI TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_PROCEDIMENT TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_PROCEDIMENT_SERVEI TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_SERVEI_CAMP TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_SERVEI_BUS TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_USUARI TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON SCSP_CODIGO_ERROR TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON SCSP_ESTADO_PETICION TO WWW_PINBAL;

GRANT SELECT ON HIBERNATE_SEQUENCE TO WWW_PINBAL;

ALTER TABLE PBL_SERVEI_CONFIG move lob (AJUDA) store as PBL_SERVEI_CONFIG_CONT_LOB (tablespace PINBAL_LOB);