ALTER TABLE PBL_ENTITAT DROP COLUMN RESPONSABLE;
ALTER TABLE PBL_PROCEDIMENT ADD DEPARTAMENT VARCHAR2(64);

ALTER TABLE PBL_CONSULTA MODIFY PETICION_ID VARCHAR2(26);
ALTER TABLE PBL_CONSULTA MODIFY TITULAR_DOCNUM VARCHAR2(14);
ALTER TABLE PBL_CONSULTA MODIFY TITULAR_LLING1 VARCHAR2(40);
ALTER TABLE PBL_CONSULTA MODIFY TITULAR_LLING2 VARCHAR2(40);
ALTER TABLE PBL_CONSULTA MODIFY TITULAR_NOM VARCHAR2(40);
ALTER TABLE PBL_CONSULTA ADD TITULAR_NOMCOMPLET VARCHAR2(122);

ALTER TABLE PBL_SERVEI_CONFIG DROP COLUMN ACTIU_CAMP_EXP;
ALTER TABLE PBL_SERVEI_CONFIG ADD ACTIU_CAMP_NOMCOMP NUMBER(1);
UPDATE PBL_SERVEI_CONFIG SET ACTIU_CAMP_NOMCOMP=0;

ALTER TABLE PBL_CONSULTA ADD FUNCIONARI_NOM VARCHAR2(128 CHAR);
UPDATE PBL_CONSULTA C SET C.FUNCIONARI_NOM = (SELECT T.NOMBREFUNCIONARIO FROM CORE_TRANSMISION T WHERE T.IDPETICION = C.PETICION_ID);
ALTER TABLE PBL_CONSULTA ADD FUNCIONARI_DOCNUM VARCHAR2(16 CHAR);
UPDATE PBL_CONSULTA C SET C.FUNCIONARI_DOCNUM = (SELECT T.DOCFUNCIONARIO FROM CORE_TRANSMISION T WHERE T.IDPETICION = C.PETICION_ID);

ALTER TABLE PBL_SERVEI_CONFIG ADD ACTIU_CAMP_DOC NUMBER(1);
UPDATE PBL_SERVEI_CONFIG SC SET SC.ACTIU_CAMP_DOC = 1;

ALTER TABLE CORE_TRANSMISION MODIFY DOCTITULAR NULL;

ALTER TABLE PBL_USUARI MODIFY NIF NULL;
