CREATE TABLE ACL_SID(
  ID NUMBER(19) NOT NULL,
  PRINCIPAL NUMBER(1) NOT NULL,
  SID VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT ACL_SID_PK PRIMARY KEY (ID),
  CONSTRAINT ACL_SID_UK UNIQUE(SID, PRINCIPAL));

CREATE SEQUENCE ACL_SID_SEQ;

CREATE TABLE ACL_CLASS(
  ID NUMBER(19) NOT NULL,
  CLASS VARCHAR2(100 CHAR) NOT NULL,
  CONSTRAINT ACL_CLASS_PK PRIMARY KEY (ID),
  CONSTRAINT ACL_CLASS_UK UNIQUE(CLASS));

CREATE SEQUENCE ACL_CLASS_SEQ;
 
CREATE TABLE ACL_OBJECT_IDENTITY(
  ID NUMBER(19) NOT NULL,
  OBJECT_ID_CLASS NUMBER(19) NOT NULL,
  OBJECT_ID_IDENTITY NUMBER(19) NOT NULL,
  PARENT_OBJECT NUMBER(19),
  OWNER_SID NUMBER(19),
  ENTRIES_INHERITING NUMBER(1) NOT NULL,
  CONSTRAINT ACL_OID_PK PRIMARY KEY (ID),
  CONSTRAINT ACL_OID_UK UNIQUE(OBJECT_ID_CLASS, OBJECT_ID_IDENTITY),
  CONSTRAINT ACL_OID_OID_FK FOREIGN KEY(PARENT_OBJECT) REFERENCES ACL_OBJECT_IDENTITY(ID) ON DELETE CASCADE,
  CONSTRAINT ACL_OID_CLASS_FK FOREIGN KEY(OBJECT_ID_CLASS) REFERENCES ACL_CLASS(ID) ON DELETE CASCADE,
  CONSTRAINT ACL_OID_SID_FK FOREIGN KEY(OWNER_SID) REFERENCES ACL_SID(ID) ON DELETE CASCADE);

CREATE SEQUENCE ACL_OID_SEQ;

CREATE TABLE ACL_ENTRY(
  ID NUMBER(19) NOT NULL,
  ACL_OBJECT_IDENTITY NUMBER(19) NOT NULL,
  ACE_ORDER NUMBER(10) NOT NULL,
  SID NUMBER(19) NOT NULL,
  MASK NUMBER(10) NOT NULL,
  GRANTING NUMBER(1) NOT NULL,
  AUDIT_SUCCESS NUMBER(1) NOT NULL,
  AUDIT_FAILURE NUMBER(1) NOT NULL,
  CONSTRAINT ACL_ENTRY_PK PRIMARY KEY (ID),
  CONSTRAINT ACL_ENTRY_UK UNIQUE(ACL_OBJECT_IDENTITY, ACE_ORDER),
  CONSTRAINT ACL_ENTRY_OID_FK FOREIGN KEY(ACL_OBJECT_IDENTITY) REFERENCES ACL_OBJECT_IDENTITY(ID),
  CONSTRAINT ACL_ENTRY_SID_FK FOREIGN KEY(SID) REFERENCES ACL_SID(ID));

CREATE SEQUENCE ACL_ENTRY_SEQ;

CREATE OR REPLACE TRIGGER ACL_SID_TRG
BEFORE INSERT ON ACL_SID
FOR EACH ROW
BEGIN
SELECT ACL_SID_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER ACL_CLASS_TRG
BEFORE INSERT ON ACL_CLASS
FOR EACH ROW
BEGIN
SELECT ACL_CLASS_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER ACL_OID_TRG
BEFORE INSERT ON ACL_OBJECT_IDENTITY
FOR EACH ROW
BEGIN
SELECT ACL_OID_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/

CREATE OR REPLACE TRIGGER ACL_ENTRY_TRG
BEFORE INSERT ON ACL_ENTRY
FOR EACH ROW
BEGIN
SELECT ACL_ENTRY_SEQ.NEXTVAL INTO :NEW.ID FROM dual;
END;
/
