ALTER TABLE PBL_MON_INT MODIFY DESCRIPCIO VARCHAR2(1024 CHAR);
ALTER TABLE PBL_MON_INT MODIFY ERROR_DESCRIPCIO VARCHAR2(1024 CHAR);
ALTER TABLE PBL_MON_INT MODIFY EXCEPCIO_MSG VARCHAR2(1024 CHAR);
ALTER TABLE PBL_MON_INT MODIFY EXCEPCIO_STACKTRACE VARCHAR2(2048 CHAR);