<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" targetNamespace="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="DatosEspecificos">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="Consulta"/>
				<xs:element ref="Retorno"/>
			</xs:choice>
			<xs:attribute name="Id" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Consulta">
		<xs:annotation>
			<xs:documentation>Datos de consulta para el servicio de solicitar apostilla de documento</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="CodigoAplicacion"/>
				<xs:element ref="Solicitante"/>
				<xs:element ref="CodigoPaisDestino"/>
				<xs:element ref="DatosDocumento"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="Retorno">
		<xs:annotation>
			<xs:documentation>Datos de retorno para el servicio de solicitar apostilla de documento</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="Estado"/>
				<xs:element ref="Apostilla"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="Estado">
		<xs:complexType>
			<xs:all>
				<xs:element ref="CodigoEstado"/>
				<xs:element ref="Literal"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="CodigoEstado">
		<xs:annotation>
			<xs:documentation>Codigo de estado</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="4"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Literal">
		<xs:annotation>
			<xs:documentation>Descripcion del estado</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="1024"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Apostilla">
		<xs:annotation>
			<xs:documentation>Datos de la apostilla recibida</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="NumeroApostilla"/>
				<xs:element ref="Documento" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Contenido binario (en base64)  de la apostilla en PDF</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="CSV" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="CodigoAplicacion">
		<xs:annotation>
			<xs:documentation>Codigo de la aplicación invocante indicada por el cedente</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:length value="2"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Solicitante">
		<xs:annotation>
			<xs:documentation>Datos del solicitante del documento a apostillar</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Direccion" minOccurs="0"/>
				<xs:element ref="CodigoPostal" minOccurs="0"/>
				<xs:element ref="Municipio" minOccurs="0"/>
				<xs:element ref="CodigoProvincia"/>
				<xs:element ref="CodigoPais"/>
				<xs:element ref="Email" minOccurs="0"/>
				<xs:element ref="Telefono" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Direccion">
		<xs:annotation>
			<xs:documentation>Dirección postal del domicilio del solicitante</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="150"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoPostal">
		<xs:annotation>
			<xs:documentation>Código postal del domicilio del solicitante</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{5}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Municipio">
		<xs:annotation>
			<xs:documentation>Nombre del municipio del domicilio del solicitante</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="150"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoProvincia">
		<xs:annotation>
			<xs:documentation>Código de provincia del domicilio del solicitante. Codificación INE</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:int">
				<xs:minInclusive value="01"/>
				<xs:maxInclusive value="52"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoPais">
		<xs:annotation>
			<xs:documentation>Código de país del domicilio del solicitante. Codificación ISO 3166-1 Numérico</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:int">
				<xs:pattern value="\d{3}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoPaisDestino">
		<xs:annotation>
			<xs:documentation>Código de país destinatario de la Apostilla. Codificación ISO 3166-1 Numérico</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:int">
				<xs:pattern value="\d{3}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Email">
		<xs:annotation>
			<xs:documentation>Dirección de correo electrónico de contacto del solicitante</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="100"/>
				<xs:pattern value="[^@]+@[^\.]+\..+"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Telefono">
		<xs:annotation>
			<xs:documentation>Número de teléfono de contacto del solicitante</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:whiteSpace value="collapse"/>
				<xs:pattern value="(\+)?[0-9]{1,20}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DatosDocumento">
		<xs:annotation>
			<xs:documentation>Datos del documento que se quiere apostillar</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Descripcion"/>
				<xs:element ref="Tipo" minOccurs="0"/>
				<xs:element ref="Extension"/>
				<xs:element ref="CSV" minOccurs="0"/>
				<xs:element ref="Firmante" minOccurs="0"/>
				<xs:element ref="Documento">
					<xs:annotation>
						<xs:documentation>Contenido binario (en base64) del Documento Público, se recomienda en formato PDF</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Descripcion">
		<xs:annotation>
			<xs:documentation>Descripción textual del Documento Público a ser apostillado</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="250"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Tipo">
		<xs:annotation>
			<xs:documentation>Código del tipo de documento
- ACA - Certificado académico
- ADO - Adopción
- BOE - BOE
- DGT - DGT
- CIV - Registro civil
- DEF - Defunción
- DGP - DGP
- DNI - DNI
- EMP - Empleo
- HAC - Hacienda
- JUD - Judicial
- LAB - Vida laboral
- LIB - Libro de familia
- MAT - Matrimonio
- MEI - Medicamento
- MED - Médico
- MER - Registro mercantil
- MIR - MIR
- NAO - Certificado de nacimiento
- NAD - Nacionalidad
- OTR - Otros
- PAD - Padrón
- PAS - Pasaporte
- PEN - Certificado de antecedentes penales
- RES - Residencia
- SEG - Seguridad social
- TRA - Trabajo
- ULT - Últimas voluntades
- VEN - Libre venta
- VID - Fe de Vida
</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="ACA"/>
				<xs:enumeration value="ADO"/>
				<xs:enumeration value="BOE"/>
				<xs:enumeration value="DGT"/>
				<xs:enumeration value="CIV"/>
				<xs:enumeration value="DEF"/>
				<xs:enumeration value="DGP"/>
				<xs:enumeration value="DNI"/>
				<xs:enumeration value="EMP"/>
				<xs:enumeration value="HAC"/>
				<xs:enumeration value="JUD"/>
				<xs:enumeration value="LAB"/>
				<xs:enumeration value="LIB"/>
				<xs:enumeration value="MAT"/>
				<xs:enumeration value="MEI"/>
				<xs:enumeration value="MED"/>
				<xs:enumeration value="MER"/>
				<xs:enumeration value="MIR"/>
				<xs:enumeration value="NAO"/>
				<xs:enumeration value="NAD"/>
				<xs:enumeration value="OTR"/>
				<xs:enumeration value="PAD"/>
				<xs:enumeration value="PAS"/>
				<xs:enumeration value="PEN"/>
				<xs:enumeration value="RES"/>
				<xs:enumeration value="SEG"/>
				<xs:enumeration value="TRA"/>
				<xs:enumeration value="ULT"/>
				<xs:enumeration value="VEN"/>
				<xs:enumeration value="VID"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Extension">
		<xs:annotation>
			<xs:documentation>Extensión de nombre de archivo que correspondería al Documento Público y que es indicativa de su tipo
Para Documentos XAdES
- xml
- xsig
Para Documentos PAdES
- pdf
Para Documentos CAdES
- csig
- p7s
</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="xml"/>
				<xs:enumeration value="xsig"/>
				<xs:enumeration value="pdf"/>
				<xs:enumeration value="csig"/>
				<xs:enumeration value="p7s"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CSV">
		<xs:annotation>
			<xs:documentation>Código Seguro de Verificación del Documento Público</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="100"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Firmante">
		<xs:annotation>
			<xs:documentation>Datos del firmante del documento que se solicita apostillar</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="Nombre" minOccurs="0"/>
				<xs:element ref="Calidad" minOccurs="0"/>
				<xs:element ref="Organismo" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="Nombre">
		<xs:annotation>
			<xs:documentation>Nombre del firmante del documento a apostillar, si no se indica se tomará como nombre el del certificado firmante deld ocumento enviado</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="150"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Calidad">
		<xs:annotation>
			<xs:documentation>Calidad (cargo) del firmante del documento a apostillar, si no se indica se tomará como calidad del firmanto el del certificado firmante deld ocumento enviado</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="250"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Organismo">
		<xs:annotation>
			<xs:documentation>Organismo al que pertenece el firmante del documento a apostillar, si no se indica se tomará como organismo el del certificado firmante del documento enviado</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="250"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Documento">
		<xs:simpleType>
			<xs:restriction base="xs:base64Binary">
				<xs:minLength value="1"/>
				<xs:maxLength value="2097152"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="NumeroApostilla">
		<xs:annotation>
			<xs:documentation>Número asignado a la Apostilla</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:length value="17"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>
