-- #298

CREATE TABLE PBL_MON_INT (
	ID NUMBER(19,0),
	CODI VARCHAR2(64),
	"DATA" TIMESTAMP,
	DESCRIPCIO VARCHAR2(1024),
	TIPUS VARCHAR2(10),
	TEMPS_RESPOSTA NUMBER(19,0),
	ESTAT VARCHAR2(5),
	CODI_USUARI VARCHAR2(64),
	ERROR_DESCRIPCIO VARCHAR2(1024),
	EXCEPCIO_MSG VARCHAR2(1024),
	EXCEPCIO_STACKTRACE VARCHAR2(2048),
	CODI_ENTITAT VARCHAR2(64),
	CREATEDBY_CODI VARCHAR2(64),
	CREATEDDATE TIMESTAMP,
	LASTMODIFIEDBY_CODI VARCHAR2(64),
	LASTMODIFIEDDATE TIMESTAMP,
	ID_PETICIO VARCHAR2(64),
	CONSTRAINT PBL_MON_INT_PK PRIMARY KEY (ID),
	CONSTRAINT SYS_C00283243 CHECK ("ID" IS NOT NULL),
	CONSTRAINT SYS_C00283244 CHECK ("CODI" IS NOT NULL)
);
CREATE UNIQUE INDEX PBL_MON_INT_PK ON PBL_MON_INT (ID);

CREATE TABLE PBL_MON_INT_PARAM (
	ID NUMBER(19,0),
	MON_INT_ID NUMBER(19,0),
	NOM VARCHAR2(64),
	DESCRIPCIO VARCHAR2(1024),
	CREATEDBY_CODI VARCHAR2(64),
	CREATEDDATE TIMESTAMP,
	LASTMODIFIEDBY_CODI VARCHAR2(64),
	LASTMODIFIEDDATE TIMESTAMP,
	CONSTRAINT PBL_MON_INT_PARAM_PK PRIMARY KEY (ID),
	CONSTRAINT SYS_C00283278 CHECK ("ID" IS NOT NULL),
	CONSTRAINT SYS_C00283279 CHECK ("MON_INT_ID" IS NOT NULL),
	CONSTRAINT SYS_C00283280 CHECK ("NOM" IS NOT NULL),
	CONSTRAINT DIS_MONINTPARAM_MONINT_FK FOREIGN KEY (MON_INT_ID) REFERENCES PBL_MON_INT(ID)
);
CREATE UNIQUE INDEX PBL_MON_INT_PARAM_PK ON PBL_MON_INT_PARAM (ID);

