-- #298

CREATE TABLE PBL_MON_INT (
     ID NUMBER(19,0) NOT NULL ,
     CODI VARCHAR2(64) NOT NULL ,
     "DATA" TIMESTAMP,
     DESCRIPCIO VARCHAR2(1024),
     TIPUS VARCHAR2(10),
     TEMPS_RESPOSTA NUMBER(19,0),
     ESTAT VARCHAR2(5),
     CODI_USUARI VARCHAR2(64),
     ERROR_DESCRIPCIO VARCHAR2(1024),
     EXCEPCIO_MSG VARCHAR2(1024),
     EXCEPCIO_STACKTRACE VARCHAR2(2048),
     CODI_ENTITAT VARCHAR2(64),
     CREATEDBY_CODI VARCHAR2(64),
     CREATEDDATE TIMESTAMP,
     LASTMODIFIEDBY_CODI VARCHAR2(64),
     LASTMODIFIEDDATE TIMESTAMP,
     ID_PETICIO VARCHAR2(64),
     CONSTRAINT PBL_MON_INT_PK PRIMARY KEY (ID)
);

CREATE TABLE PBL_MON_INT_PARAM (
    ID NUMBER(19,0) NOT NULL ,
    MON_INT_ID NUMBER(19,0) NOT NULL ,
    NOM VARCHAR2(64) NOT NULL ,
    DESCRIPCIO VARCHAR2(1024),
    CREATEDBY_CODI VARCHAR2(64),
    CREATEDDATE TIMESTAMP,
    LASTMODIFIEDBY_CODI VARCHAR2(64),
    LASTMODIFIEDDATE TIMESTAMP,
    CONSTRAINT PBL_MON_INT_PARAM_PK PRIMARY KEY (ID),
    CONSTRAINT DIS_MONINTPARAM_MONINT_FK FOREIGN KEY (MON_INT_ID) REFERENCES PBL_MON_INT(ID)
);

GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_MON_INT TO WWW_PINBAL;
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_MON_INT_PARAM TO WWW_PINBAL;

-- #311
ALTER TABLE PBL_SERVEI_CAMP ADD MIDA NUMBER(38,0);

-- #282
ALTER TABLE pbl_usuari ADD num_elements_pagina INTEGER DEFAULT '10';

-- #332
CREATE TABLE pbl_servei_xsd
(
    id        NUMBER(38, 0) NOT NULL,
    servei_id VARCHAR2(64 CHAR) NOT NULL,
    tipus     VARCHAR2(32 CHAR) NOT NULL,
    path      VARCHAR2(255 CHAR) NOT NULL,
    nomarxiu  VARCHAR2(255 CHAR) NOT NULL,
    version   NUMBER(38, 0) NOT NULL,
    data      TIMESTAMP NOT NULL,
    CONSTRAINT PK_PBL_SERVEI_XSD PRIMARY KEY (id)
);
ALTER TABLE pbl_servei_xsd ADD CONSTRAINT pbl_servei_xsd_uk UNIQUE (servei_id, tipus);
CREATE INDEX pbl_servei_xsd_servei_i ON pbl_servei_xsd (servei_id);

GRANT SELECT, UPDATE, INSERT, DELETE ON pbl_servei_xsd TO WWW_PINBAL;

-- Afegir TER
ALTER TABLE pbl_consulta ADD der TIMESTAMP;
ALTER TABLE pbl_consulta_hist ADD der TIMESTAMP;
ALTER TABLE pbl_consulta_list ADD der TIMESTAMP;
ALTER TABLE pbl_consulta_hist_list ADD der TIMESTAMP;

-- Changeset db/changelog/changes/1.4.42/sia_origen.yaml::add-codi-sia-origen-column::limit
ALTER TABLE PBL_PROCEDIMENT ADD CODI_SIA_ORIGEN VARCHAR2(64 CHAR);


