CREATE INDEX PBL_CONSULTA_CREATBY_I ON PBL_CONSULTA (CREATEDBY_CODI);
CREATE INDEX PBL_CONSULTA_MODIFBY_I ON PBL_CONSULTA (LASTMODIFIEDBY_CODI);

CREATE INDEX PBL_CONSULTAH_CREATBY_I ON PBL_CONSULTA_HIST (CREATEDBY_CODI);
CREATE INDEX PBL_CONSULTAH_MODIFBY_I ON PBL_CONSULTA_HIST (LASTMODIFIEDBY_CODI);

CREATE INDEX PBL_MON_INT_CREATBY_I ON PBL_MON_INT (CREATEDBY_CODI);
CREATE INDEX PBL_MON_INT_MODIFBY_I ON PBL_MON_INT (LASTMODIFIEDBY_CODI);

CREATE INDEX PBL_MON_PARAM_CREATBY_I ON PBL_MON_INT_PARAM (CREATEDBY_CODI);
CREATE INDEX PBL_MON_PARAM_MODIFBY_I ON PBL_MON_INT_PARAM (LASTMODIFIEDBY_CODI);

CREATE INDEX PBL_CONSULTAL_CREATBY_I ON PBL_CONSULTA_LIST (USUARICODI);
CREATE INDEX PBL_CONSULTAHL_MODIFBY_I ON PBL_CONSULTA_HIST_LIST (USUARICODI);

CREATE INDEX PBL_CONSULTAL_DATA_I ON PBL_CONSULTA_LIST (data);
CREATE INDEX PBL_CONSULTAHL_DATA_I ON PBL_CONSULTA_HIST_LIST (data);