create table pbl_acl_class (
    id bigint generated by default as identity primary key,
    class varchar(100) not null,
    class_id_type varchar(100)
);

create table pbl_acl_sid (
    id bigint generated by default as identity primary key,
    principal boolean not null,
    sid varchar(100) not null
);

create table pbl_acl_object_identity (
    id bigint generated by default as identity primary key,
    object_id_class bigint not null,
    object_id_identity bigint not null,
    parent_object bigint,
    owner_sid bigint not null,
    entries_inheriting boolean not null,
    foreign key (object_id_class) references pbl_acl_class(id),
    foreign key (parent_object) references pbl_acl_object_identity(id),
    foreign key (owner_sid) references pbl_acl_sid(id)
);

create table pbl_acl_entry (
    id bigint generated by default as identity primary key,
    acl_object_identity bigint not null,
    sid bigint not null,
    ace_order int not null,
    mask int not null,
    granting boolean not null,
    audit_success boolean not null,
    audit_failure boolean not null,
    foreign key (acl_object_identity) references pbl_acl_object_identity(id),
    foreign key (sid) references pbl_acl_sid(id)
);
