ALTER TABLE PBL_PROCEDIMENT
ADD (
    CODI_SIA VARCHAR2(64)
);
ALTER TABLE PBL_CONSULTA
ADD (
    ARXIU_EXPEDIENT_UUID VARCHAR2(100),
    ARXIU_DOCUMENT_UUID VARCHAR2(100)
);
ALTER TABLE PBL_CONSULTA ADD ARXIU_EXPEDIENT_TANCAT NUMBER(1) DEFAULT 0;
