----
-- issue 62
----

ALTER TABLE PBL_ENTITAT
ADD (
    UNITAT_ARREL VARCHAR2(9)
);

CREATE TABLE PBL_ORGAN_GESTOR
(
	ID			NUMBER(19)		NOT NULL,
	CODI		VARCHAR2(64)	NOT NULL,
	NOM			VARCHAR2(1000)	NOT NULL,
  	ENTITAT_ID	NUMBER(19)		NOT NULL,
  	PARE_ID NUMBER(19),
  	ACTIU NUMBER(1,0) DEFAULT 1 NOT NULL,
  	
  	CREATEDBY_CODI VARCHAR2(64),
    CREATEDDATE TIMESTAMP(6),
    LASTMODIFIEDBY_CODI VARCHAR2(64),
    LASTMODIFIEDDATE TIMESTAMP(6),
    
  	CONSTRAINT PBL_ORGAN_GESTOR_PK PRIMARY KEY (ID),
  	CONSTRAINT PBL_ENTITAT_ORGAN_GESTOR_FK FOREIGN KEY (ENTITAT_ID) REFERENCES PBL_ENTITAT (ID),
  	CONSTRAINT PBL_ORGAN_GESTOR_UK UNIQUE (CODI, ENTITAT_ID)
);
GRANT SELECT, UPDATE, INSERT, DELETE ON PBL_ORGAN_GESTOR TO WWW_PINBAL;

ALTER TABLE PBL_PROCEDIMENT
ADD (
    ORGAN_GESTOR_ID NUMBER(19),
    CONSTRAINT PBL_ORGAN_PROCEDIMENT_FK FOREIGN KEY (ORGAN_GESTOR_ID) REFERENCES PBL_ORGAN_GESTOR (ID)
);  


----
-- issue 68
----

ALTER TABLE PBL_PROCEDIMENT
ADD (
    CODI_SIA VARCHAR2(64)
);
ALTER TABLE PBL_CONSULTA
ADD (
    ARXIU_EXPEDIENT_UUID VARCHAR2(100),
    ARXIU_DOCUMENT_UUID VARCHAR2(100)
);
ALTER TABLE PBL_CONSULTA ADD ARXIU_EXPEDIENT_TANCAT NUMBER(1) DEFAULT 0;