server:
  servlet:
    context-path: /pinbalback
  error:
    path: /error
  forward-headers-strategy: framework

spring:
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.Oracle12cDialect
#        hbm2ddl.auto: validate
#        show_sql: false
#        format_sql: true
#        use_sql_comments: true
#    hibernate:
#      naming-strategy: es.caib.pinbal.persist.audit.CustomPhysicalNamingStrategy
#      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
#    open-in-view: false

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  freemarker.enabled: false
  messages.basename: messages
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
  jackson.default-property-inclusion: non_null

#  liquibase:
#    enabled: true
#    database-change-log-table: NOT_DATABASECHANGELOG
#    database-change-log-lock-table: NOT_DATABASECHANGELOGLOCK
#    change-log: classpath:/db/changelog/db.changelog-master.yaml
#    labels: none

  cache.jcache.config: classpath:ehcache.xml

  jmx.enabled: true

  management.endpoints.jmx.exposure.include: "*"

  autoconfigure.exclude: org.springframework.boot.actuate.autoconfigure.metrics.jersey.JerseyServerMetricsAutoConfiguration
