<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" targetNamespace="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="DatosEspecificos">
		<xs:annotation>
			<xs:documentation>Datos Especificos del proyecto de tarjeta social universal</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="DatosEspecificos"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="DatosEspecificos">
		<xs:choice>
			<xs:element name="Comunicacion">
				<xs:annotation>
					<xs:documentation>Datos de la comunicación de los pagos</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="Pago"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Respuesta">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Estado" maxOccurs="5">
							<xs:annotation>
								<xs:documentation>Estado de la comunicación de pagos se pueden devolver hasta 5 códigos de error.</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:all>
									<xs:element ref="CodigoEstado"/>
									<xs:element ref="LiteralError"/>
									<xs:element ref="CodigoEstadoSecundario" minOccurs="0"/>
								</xs:all>
							</xs:complexType>
						</xs:element>
						<xs:element ref="InformacionAdicional" minOccurs="0"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:choice>
		<xs:attribute name="Id" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:element name="Pago">
		<xs:annotation>
			<xs:documentation>Datos del pago de la prestación</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="ClavePropiaEntidad"/>
				<xs:element ref="Ejercicio"/>
				<xs:element ref="FechaInicioPago"/>
				<xs:element ref="FechaFinPago"/>
				<xs:element ref="ClasePago"/>
				<xs:element ref="SituacionPago"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="ClavePropiaEntidad">
		<xs:annotation>
			<xs:documentation>Clave única que identifica el pago de una prestación, debe tener formato DIR3+Clavepropia e identifica a la prestación ya concedida</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="40"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Ejercicio">
		<xs:annotation>
			<xs:documentation>Ejercicio al que hace referencia el pago</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:int">
				<xs:minInclusive value="1900"/>
				<xs:totalDigits value="4"/>
				<xs:pattern value="\d{4}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FechaInicioPago">
		<xs:annotation>
			<xs:documentation>Fecha de inicio del pago</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:date">
				<xs:minInclusive value="1900-01-01"/>
				<xs:pattern value="\d{4}-\d{2}-\d{2}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FechaFinPago">
		<xs:annotation>
			<xs:documentation>Fecha de fin del pago</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:date">
				<xs:minInclusive value="1900-01-01"/>
				<xs:pattern value="\d{4}-\d{2}-\d{2}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ClasePago">
		<xs:annotation>
			<xs:documentation>Código que identifica la clase de pago</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="01"/>
				<xs:enumeration value="02"/>
				<xs:enumeration value="03"/>
				<xs:enumeration value="04"/>
				<xs:enumeration value="05"/>
				<xs:enumeration value="06"/>
				<xs:enumeration value="07"/>
				<xs:enumeration value="08"/>
				<xs:enumeration value="09"/>
				<xs:enumeration value="12"/>
				<xs:enumeration value="13"/>
				<xs:enumeration value="20"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="SituacionPago">
		<xs:annotation>
			<xs:documentation>Código que identifica la situación del pago</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="PA"/>
				<xs:enumeration value="NP"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoEstado">
		<xs:annotation>
			<xs:documentation>Código de estado de la respuesta de la solicitud.</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="5"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="LiteralError">
		<xs:annotation>
			<xs:documentation>Literal de estado de la respuesta de la solicitud.</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="1024"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoEstadoSecundario">
		<xs:annotation>
			<xs:documentation>Código secundario de estado de la respuesta de la solicitud.</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="16"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="InformacionAdicional">
		<xs:annotation>
			<xs:documentation>Información adicional asociada al primer código de respuesta</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="50"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>
