<!-- edited with XMLSpy v2011 sp1 (http://www.altova.com) by End User (free.org) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" targetNamespace="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="DatosEspecificos" type="DatosEspecificos"/>
	<xs:complexType name="DatosEspecificos">
		<xs:choice>
			<xs:element ref="Solicitud"/>
			<xs:element ref="Retorno">
				<xs:annotation>
					<xs:documentation>Solo en el mensaje RESPUESTA</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:choice>
		<xs:attribute name="Id" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:element name="Retorno">
		<xs:complexType>
			<xs:all>
				<xs:element ref="Estado"/>
				<xs:element ref="FechaInscripcion" minOccurs="0"/>
				<xs:element ref="Domicilio" minOccurs="0"/>
				<xs:element ref="OrigenDatos" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="Estado">
		<xs:complexType>
			<xs:all>
				<xs:element ref="CodigoEstado"/>
				<xs:element ref="CodigoEstadoSecundario" minOccurs="0"/>
				<xs:element ref="LiteralError"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="CodigoEstado">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="4"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoEstadoSecundario">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="16"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="LiteralError">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="1024"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Domicilio">
		<xs:complexType>
			<xs:all>
				<xs:element ref="ProvinciaRespuesta" minOccurs="0"/>
				<xs:element ref="MunicipioRespuesta" minOccurs="0"/>
				<xs:element ref="EntColectiva" minOccurs="0"/>
				<xs:element ref="EntSingular" minOccurs="0"/>
				<xs:element ref="Nucleo" minOccurs="0"/>
				<xs:element ref="CodUnidadPoblacional" minOccurs="0"/>
				<xs:element ref="Direccion" minOccurs="0"/>
				<xs:element ref="UltimaVariacion" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="OrigenDatos">
		<xs:complexType>
			<xs:all>
				<xs:element name="Provincia" type="CodigoProvincia"/>
				<xs:element name="Municipio" type="CodigoMunicipio"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="ProvinciaRespuesta">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Codigo" type="CodigoProvincia"/>
				<xs:element name="Nombre" type="Provincia" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="CodigoProvincia">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{1,2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Provincia">
		<xs:restriction base="xs:string">
			<xs:maxLength value="70"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CodigoMunicipio">
		<xs:restriction base="xs:string">
			<xs:pattern value="\d{1,3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Municipio">
		<xs:restriction base="xs:string">
			<xs:maxLength value="70"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="CodUnidadPoblacional">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="7"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="MunicipioRespuesta">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Codigo">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="3"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Nombre" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="70"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="EntColectiva">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Codigo">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="2"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Nombre" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="70"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="EntSingular">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Codigo">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="2"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Nombre" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="70"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Nucleo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Codigo">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="2"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Nombre" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="70"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Direccion">
		<xs:complexType>
			<xs:all>
				<xs:element ref="Via" minOccurs="0"/>
				<xs:element ref="Numero" minOccurs="0"/>
				<xs:element ref="NumeroSuperior" minOccurs="0"/>
				<xs:element ref="Kmt" minOccurs="0"/>
				<xs:element ref="Hmt" minOccurs="0"/>
				<xs:element ref="Bloque" minOccurs="0"/>
				<xs:element ref="Portal" minOccurs="0"/>
				<xs:element ref="Escalera" minOccurs="0"/>
				<xs:element ref="Planta" minOccurs="0"/>
				<xs:element ref="Puerta" minOccurs="0"/>
				<xs:element ref="CodPostal" minOccurs="0"/>
				<xs:element ref="TipoLocal" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="Via">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Codigo" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="5"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Tipo">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="5"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Nombre">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="70"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element ref="Pseudovia" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Numero">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Calificador">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Valor">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="4"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="NumeroSuperior">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Calificador">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Valor">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="4"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CodPostal">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="5"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="TipoLocal">
		<xs:annotation>
			<xs:documentation>Tipo de local de la dirección del domicilio</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="1"/>
				<xs:maxInclusive value="2"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="UltimaVariacion">
		<xs:complexType>
			<xs:all>
				<xs:element name="Codigo" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string"/>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Descripcion" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string"/>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Fecha" minOccurs="0">
					<xs:simpleType>
						<xs:restriction base="xs:string"/>
					</xs:simpleType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="Documentacion">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="14"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Solicitud">
		<xs:annotation>
			<xs:documentation>Solo en el mensaje de PETICION</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="Residencia"/>
				<xs:element ref="Nacimiento" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="Nacimiento">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Fecha" minOccurs="0"/>
				<xs:choice minOccurs="0">
					<xs:element name="PaisNacimiento" type="CodigoPais"/>
					<xs:sequence>
						<xs:element name="Provincia" type="CodigoProvincia"/>
						<xs:element name="Municipio" type="CodigoMunicipio" minOccurs="0"/>
					</xs:sequence>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Fecha">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="8"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Residencia">
		<xs:complexType>
			<xs:all>
				<xs:element name="Provincia" type="CodigoProvincia"/>
				<xs:element name="Municipio" type="CodigoMunicipio"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="Kmt">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="3"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Hmt">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="1"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Bloque">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="2"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Portal">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="2"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Escalera">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="2"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Planta">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="3"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Puerta">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="4"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:simpleType name="CodigoPais">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="collapse"/>
			<xs:pattern value="\d{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Pseudovia">
		<xs:annotation>
			<xs:documentation>Pseudovia de la vía de la dirección</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="50"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FechaInscripcion">
		<xs:simpleType>
			<xs:restriction base="xs:date"/>
		</xs:simpleType>
	</xs:element>
</xs:schema>
