<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" elementFormDefault="qualified">
	<xs:element name="DatosEspecificos" type="DatosEspecificos"/>
	<xs:complexType name="DatosEspecificos">
		<xs:all>
			<xs:element ref="Retorno">
				<xs:annotation>
					<xs:documentation>Solo en el mensaje RESPUESTA</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:all>
		<xs:attribute name="Id" type="xs:string" use="optional"/>
	</xs:complexType>
	<!-- Datos de retorno -->
	<xs:element name="Retorno">
		<xs:complexType>
			<xs:all>
				<xs:element ref="Estado"/>
				<xs:element ref="Titulos" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<!-- Datos Estado -->
	<xs:element name="Estado">
		<xs:annotation>
			<xs:documentation>Estado de la transmisión</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="CodigoEstado"/>
				<xs:element ref="CodigoEstadoSecundario" minOccurs="0"/>
				<xs:element ref="LiteralError"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="CodigoEstado">
		<xs:annotation>
			<xs:documentation>Código de Estado de la transmisión</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="4"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoEstadoSecundario">
		<xs:annotation>
			<xs:documentation>Código de estado secundario de la transmisión</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="16"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="LiteralError">
		<xs:annotation>
			<xs:documentation>Literal del estado de la transmisión</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="5"/>
				<xs:maxLength value="1024"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Titulos">
		<xs:annotation>
			<xs:documentation>Lista de títulos del titular</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Titulo" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Titulo">
		<xs:annotation>
			<xs:documentation>Datos de cada título del titular</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="TipoTitulo">
					<xs:annotation>
						<xs:documentation>Tipo de título de competencia profesional</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element ref="FechaObtencion"/>
				<xs:element ref="FechaValidez" minOccurs="0"/>
				<xs:element ref="FormaObtencion" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="TipoTitulo">
		<xs:annotation>
			<xs:documentation>Tipo de título de competencia profesional</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Codigo">
					<xs:annotation>
						<xs:documentation>Código del tipo de título de competencia profesional.</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="01"/>
							<xs:enumeration value="02"/>
							<xs:enumeration value="03"/>
							<xs:enumeration value="04"/>
							<xs:enumeration value="05"/>
							<xs:enumeration value="06"/>
							<xs:enumeration value="07"/>
							<xs:enumeration value="08"/>
							<xs:enumeration value="09"/>
							<xs:enumeration value="10"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Denominacion">
					<xs:annotation>
						<xs:documentation>Denominación del tipo de título de competencia profesional.</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="50"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="FechaObtencion" type="xs:date">
		<xs:annotation>
			<xs:documentation>Fecha de obtención del título. Formato: AAAA-MM-DD</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="FechaValidez" type="xs:date">
		<xs:annotation>
			<xs:documentation>Fecha de validez del título. Formato: AAAA-MM-DD. Si el título tiene validez indefinida este nodo no se devolverá en la respuesta.</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="FormaObtencion">
		<xs:annotation>
			<xs:documentation>Forma de obtención del titulo</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Codigo">
					<xs:annotation>
						<xs:documentation>Código de la forma de obtención del título.</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="01"/>
							<xs:enumeration value="02"/>
							<xs:enumeration value="03"/>
							<xs:enumeration value="04"/>
							<xs:enumeration value="05"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Denominacion">
					<xs:annotation>
						<xs:documentation>Denominación  de la forma de obtención del título.</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:minLength value="1"/>
										<xs:maxLength value="25"/>
									</xs:restriction>
								</xs:simpleType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
