<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 sp1 (http://www.altova.com) by End User (free.org) -->
<xs:schema xmlns="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" elementFormDefault="qualified">
	<xs:element name="DatosEspecificos" type="DatosEspecificos"/>
	<xs:complexType name="DatosEspecificos">
		<xs:all>
			<xs:element ref="Retorno">
				<xs:annotation>
					<xs:documentation>Solo en el mensaje RESPUESTA</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:all>
		<xs:attribute name="Id" type="xs:string" use="optional"/>
	</xs:complexType>
	<!-- Datos de consulta -->
	<xs:element name="Consulta">
		<xs:complexType>
			<xs:all>
				<xs:element name="TipoDocumentacion" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="NIF"/>
							<xs:enumeration value="NIE"/>
							<xs:enumeration value="PASAPORTE"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element ref="NifPropietario" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="NombrePropietario" minOccurs="0" maxOccurs="1"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="NifPropietario">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="15"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="NombrePropietario">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="82"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<!-- Datos de retorno -->
	<xs:element name="Retorno">
		<xs:complexType>
			<xs:all>
				<xs:element ref="Estado"/>
				<xs:element ref="PropietarioBuque" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="PropietarioMoto" minOccurs="0" maxOccurs="1"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<!-- Datos Estado -->
	<xs:element name="Estado">
		<xs:annotation>
			<xs:documentation>Estado de la transmision</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="CodigoEstado"/>
				<xs:element ref="CodigoEstadoSecundario" minOccurs="0"/>
				<xs:element ref="LiteralError"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="CodigoEstado">
		<xs:annotation>
			<xs:documentation>Codigo de Estado de la transmision</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="4"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoEstadoSecundario">
		<xs:annotation>
			<xs:documentation>Codigo de estado secundario de la transmision</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="16"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="LiteralError">
		<xs:annotation>
			<xs:documentation>Literal del estado de la transmision</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="5"/>
				<xs:maxLength value="1024"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<!-- Datos propiedades -->
	<xs:element name="PropietarioBuque">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DatosPropietarioBuque" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DatosPropietarioBuque">
		<xs:complexType>
			<xs:all>
				<xs:element name="NIF" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="15"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Nombre" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="50"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Direccion" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="70"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element ref="PropiedadActual" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="PropiedadAnterior" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="PropiedadBaja" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="Fletador" minOccurs="0" maxOccurs="1"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="PropiedadActual">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DatosPropiedadActual" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DatosPropiedadActual">
		<xs:complexType>
			<xs:all>
				<xs:element name="Nib" type="xs:long" minOccurs="1" maxOccurs="1"/>
				<xs:element name="Nombre" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="40"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="MatriculaActual" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="40"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="EntidadMatricula" type="xs:long" minOccurs="1" maxOccurs="1"/>
				<xs:element name="DescripcionEntidadMatricula" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="50"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ListaMatricula" type="xs:long" minOccurs="0" maxOccurs="1"/>
				<xs:element name="FolioMatricula" type="xs:long" minOccurs="1" maxOccurs="1"/>
				<xs:element name="AnioMatricula" type="xs:long" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Imo" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="7"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Estado" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="30"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="FechaCompra" type="xs:date" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Porcentaje" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:decimal">
							<xs:minInclusive value="0"/>
							<xs:maxInclusive value="999.99"/>
							<xs:fractionDigits value="2"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="PropiedadAnterior">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DatosPropiedadAnterior" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DatosPropiedadAnterior">
		<xs:complexType>
			<xs:all>
				<xs:element name="Nib" type="xs:long" minOccurs="1" maxOccurs="1"/>
				<xs:element name="Nombre" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="40"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="MatriculaAnterior" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="40"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="EntidadMatricula" type="xs:long" minOccurs="1" maxOccurs="1"/>
				<xs:element name="DescripcionEntidadMatricula" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="50"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ListaMatricula" type="xs:long" minOccurs="1" maxOccurs="1"/>
				<xs:element name="FolioMatricula" type="xs:long" minOccurs="1" maxOccurs="1"/>
				<xs:element name="AnioMatricula" type="xs:long" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Imo" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="7"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Estado" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="30"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="FechaCompra" type="xs:date" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Porcentaje" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:decimal">
							<xs:minInclusive value="0"/>
							<xs:maxInclusive value="999.99"/>
							<xs:fractionDigits value="2"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="PropiedadBaja">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DatosPropiedadBaja" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DatosPropiedadBaja">
		<xs:complexType>
			<xs:all>
				<xs:element name="Nib" type="xs:long" minOccurs="1" maxOccurs="1"/>
				<xs:element name="Nombre" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="40"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="MatriculaBaja" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="40"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="EntidadMatricula" type="xs:long" minOccurs="1" maxOccurs="1"/>
				<xs:element name="DescripcionEntidadMatricula" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="50"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ListaMatricula" type="xs:long" minOccurs="1" maxOccurs="1"/>
				<xs:element name="FolioMatricula" type="xs:long" minOccurs="1" maxOccurs="1"/>
				<xs:element name="AnioMatricula" type="xs:long" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Imo" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="7"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Estado" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="30"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="FechaCompra" type="xs:date" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Porcentaje" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:decimal">
							<xs:minInclusive value="0"/>
							<xs:maxInclusive value="999.99"/>
							<xs:fractionDigits value="2"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="Fletador">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DatosFletador" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DatosFletador">
		<xs:complexType>
			<xs:all>
				<xs:element name="Nib" type="xs:long" minOccurs="1" maxOccurs="1"/>
				<xs:element name="MatriculaFletador" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="40"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Nombre" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="40"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="EntidadMatricula" type="xs:long" minOccurs="1" maxOccurs="1"/>
				<xs:element name="DescripcionEntidadMatricula" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="50"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="ListaMatricula" type="xs:long" minOccurs="1" maxOccurs="1"/>
				<xs:element name="FolioMatricula" type="xs:long" minOccurs="1" maxOccurs="1"/>
				<xs:element name="AnioMatricula" type="xs:long" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Imo" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="7"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="FechaInicio" type="xs:date" minOccurs="0" maxOccurs="1"/>
				<xs:element name="FechaFin" type="xs:date" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Modalidad" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="30"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="PropietarioMoto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DatosPropietarioMoto" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DatosPropietarioMoto">
		<xs:complexType>
			<xs:all>
				<xs:element name="NIF" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="30"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Nombre" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="82"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Direccion" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="82"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element ref="MotosActual" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="MotosAnterior" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="MotosRenting" minOccurs="0" maxOccurs="1"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="MotosActual">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DatosMotosActual" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DatosMotosActual">
		<xs:complexType>
			<xs:all>
				<xs:element name="Id" type="xs:long" minOccurs="1" maxOccurs="1"/>
				<xs:element name="Matricula" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="22"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Estado" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="FechaCompra" type="xs:date" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Marca" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="25"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Modelo" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="50"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Bastidor" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="25"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Porcentaje" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:decimal">
							<xs:minInclusive value="0"/>
							<xs:maxInclusive value="999.99"/>
							<xs:fractionDigits value="2"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="MotosAnterior">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DatosMotosAnterior" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DatosMotosAnterior">
		<xs:complexType>
			<xs:all>
				<xs:element name="Id" type="xs:long" minOccurs="1" maxOccurs="1"/>
				<xs:element name="Matricula" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="22"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Estado" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="FechaCompra" type="xs:date" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Marca" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="25"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Modelo" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="50"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Bastidor" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="25"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Porcentaje" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:decimal">
							<xs:minInclusive value="0"/>
							<xs:maxInclusive value="999.99"/>
							<xs:fractionDigits value="2"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="MotosRenting">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DatosMotosRenting" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DatosMotosRenting">
		<xs:complexType>
			<xs:all>
				<xs:element name="Id" type="xs:long" minOccurs="1" maxOccurs="1"/>
				<xs:element name="Matricula" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="22"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Estado" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="1"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Marca" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="25"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Modelo" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="50"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Bastidor" minOccurs="1" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="25"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="FechaInicio" type="xs:date" minOccurs="1" maxOccurs="1"/>
				<xs:element name="FechaPrevistaFin" type="xs:date" minOccurs="0" maxOccurs="1"/>
				<xs:element name="Modalidad" minOccurs="0" maxOccurs="1">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:maxLength value="50"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
</xs:schema>
