<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>es.caib.pinbal</groupId>
		<artifactId>pinbal</artifactId>
		<version>2.0.1</version>
	</parent>
	<artifactId>pinbal-service</artifactId>
	<packaging>ejb</packaging>
	<properties>
		<liquibase.version>4.3.3</liquibase.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-acl</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-oauth2-jose</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-mail</artifactId>
		</dependency>
		<dependency>
			<groupId>com.turkraft</groupId>
			<artifactId>spring-filter</artifactId>
		</dependency>
		<dependency>
			<groupId>net.sf.jasperreports</groupId>
			<artifactId>jasperreports</artifactId>
		</dependency>
		<dependency>
			<groupId>net.sourceforge.dynamicreports</groupId>
			<artifactId>dynamicreports-core</artifactId>
		</dependency>
		<dependency>
			<groupId>dev.akkinoc.spring.boot</groupId>
			<artifactId>orika-spring-boot-starter</artifactId>
			<version>${orika.starter.version}</version>
		</dependency>
		<dependency>
			<groupId>org.ehcache</groupId>
			<artifactId>ehcache</artifactId>
		</dependency>
		<dependency>
			<groupId>org.jodconverter</groupId>
			<artifactId>jodconverter-local</artifactId>
			<version>${jodconverter.version}</version>
		</dependency>
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.document.odt</artifactId>
			<version>${xdocreport.version}</version>
		</dependency>
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.xdocreport.template.freemarker</artifactId>
			<version>${xdocreport.version}</version>
		</dependency>
		<dependency>
			<groupId>fr.opensagres.xdocreport</groupId>
			<artifactId>fr.opensagres.odfdom.converter.pdf</artifactId>
			<version>${xdocreport.version}</version>
			<exclusions>
				<exclusion>
					<artifactId>xercesImpl</artifactId>
					<groupId>xerces</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>${poi.version}</version>
		</dependency>

		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>pinbal-scsp</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>pinbal-service-intf</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>pinbal-plugin-intf</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>pinbal-plugin</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>pinbal-persistence</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>${lombok.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.jeasy</groupId>
			<artifactId>easy-rules-core</artifactId>
			<version>4.1.0</version>
			<exclusions>
				<exclusion>
					<artifactId>slf4j-api</artifactId>
					<groupId>org.slf4j</groupId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.jeasy</groupId>
			<artifactId>easy-rules-support</artifactId>
			<version>4.1.0</version>
		</dependency>
<!--		<dependency>-->
<!--			<groupId>org.hibernate</groupId>-->
<!--			<artifactId>hibernate-entitymanager</artifactId>-->
<!--			<version>${hibernate.version}</version>-->
<!--			<exclusions>-->
<!--				<exclusion>-->
<!--					<artifactId>slf4j-api</artifactId>-->
<!--					<groupId>org.slf4j</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<groupId>xml-apis</groupId>-->
<!--					<artifactId>xml-apis</artifactId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<groupId>org.apache.geronimo.specs</groupId>-->
<!--					<artifactId>geronimo-jta_1.1_spec</artifactId>-->
<!--				</exclusion>-->
<!--			</exclusions>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.hibernate</groupId>-->
<!--			<artifactId>hibernate-validator</artifactId>-->
<!--			<version>${hibernate.validator.version}</version>-->
<!--			<exclusions>-->
<!--				<exclusion>-->
<!--					<artifactId>slf4j-api</artifactId>-->
<!--					<groupId>org.slf4j</groupId>-->
<!--				</exclusion>-->
<!--			</exclusions>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.springframework</groupId>-->
<!--			<artifactId>spring-orm</artifactId>-->
<!--			<version>${spring.version}</version>-->
<!--			<type>jar</type>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.springframework</groupId>-->
<!--			<artifactId>spring-oxm</artifactId>-->
<!--			<version>${spring.version}</version>-->
<!--			<type>jar</type>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.springframework.data</groupId>-->
<!--			<artifactId>spring-data-jpa</artifactId>-->
<!--			<version>${spring-data-jpa.version}</version>-->
<!--			<exclusions>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-aop</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-beans</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-context</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-core</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-expression</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>jcl-over-slf4j</artifactId>-->
<!--					<groupId>org.slf4j</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>slf4j-api</artifactId>-->
<!--					<groupId>org.slf4j</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-beans</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-core</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-orm</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-tx</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--			</exclusions>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.springframework</groupId>-->
<!--			<artifactId>spring-aspects</artifactId>-->
<!--			<version>${spring.version}</version>-->
<!--			<type>jar</type>-->
<!--			<exclusions>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-beans</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-context</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-core</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--			</exclusions>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.springframework</groupId>-->
<!--			<artifactId>spring-expression</artifactId>-->
<!--			<version>${spring.version}</version>-->
<!--			<exclusions>-->
<!--				<exclusion>-->
<!--					<artifactId>commons-logging</artifactId>-->
<!--					<groupId>commons-logging</groupId>-->
<!--				</exclusion>-->
<!--			</exclusions>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.springframework</groupId>-->
<!--			<artifactId>spring-context-support</artifactId>-->
<!--			<version>${spring.version}</version>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.springframework.security</groupId>-->
<!--			<artifactId>spring-security-core</artifactId>-->
<!--			<version>${spring-security.version}</version>-->
<!--			<exclusions>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-aop</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-core</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-expression</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-beans</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-context</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--			</exclusions>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.springframework.security</groupId>-->
<!--			<artifactId>spring-security-acl</artifactId>-->
<!--			<version>${spring-security.version}</version>-->
<!--			<type>jar</type>-->
<!--			<exclusions>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-jdbc</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-aop</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-tx</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-core</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-context</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--			</exclusions>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.springframework.security</groupId>-->
<!--			<artifactId>spring-security-config</artifactId>-->
<!--			<version>${spring-security.version}</version>-->
<!--			<type>jar</type>-->
<!--			<exclusions>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-jdbc</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-aop</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-tx</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-core</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-beans</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-context</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--			</exclusions>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.springframework.security</groupId>-->
<!--			<artifactId>spring-security-web</artifactId>-->
<!--			<version>${spring-security.version}</version>-->
<!--			<exclusions>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-aop</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-core</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-expression</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-web</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-beans</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--				<exclusion>-->
<!--					<artifactId>spring-context</artifactId>-->
<!--					<groupId>org.springframework</groupId>-->
<!--				</exclusion>-->
<!--			</exclusions>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.fundaciobit.pluginsib.arxiu</groupId>-->
<!--			<artifactId>pluginsib-arxiu-caib</artifactId>-->
<!--			<version>${pluginsib.arxiu.version}</version>-->
<!--			<exclusions>-->
<!--				<exclusion>-->
<!--					<groupId>log4j</groupId>-->
<!--					<artifactId>log4j</artifactId>-->
<!--				</exclusion>-->
<!--			</exclusions>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>cglib</groupId>-->
<!--			<artifactId>cglib</artifactId>-->
<!--			<version>2.2</version>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>junit</groupId>-->
<!--			<artifactId>junit</artifactId>-->
<!--			<version>4.9</version>-->
<!--			<scope>test</scope>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.mockito</groupId>-->
<!--			<artifactId>mockito-core</artifactId>-->
<!--			<version>1.8.5</version>-->
<!--			<scope>test</scope>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.springframework</groupId>-->
<!--			<artifactId>spring-test</artifactId>-->
<!--			<version>${spring.version}</version>-->
<!--			<scope>test</scope>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>commons-dbcp</groupId>-->
<!--			<artifactId>commons-dbcp</artifactId>-->
<!--			<version>1.2.2</version>-->
<!--			<scope>test</scope>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>postgresql</groupId>-->
<!--			<artifactId>postgresql</artifactId>-->
<!--			<version>8.3-606.jdbc3</version>-->
<!--			<scope>test</scope>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>joda-time</groupId>-->
<!--			<artifactId>joda-time</artifactId>-->
<!--			<version>2.3</version>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>ma.glasnost.orika</groupId>-->
<!--			<artifactId>orika-core</artifactId>-->
<!--			<version>${orika.version}</version>-->
<!--			<exclusions>-->
<!--				<exclusion>-->
<!--					<artifactId>slf4j-api</artifactId>-->
<!--					<groupId>org.slf4j</groupId>-->
<!--				</exclusion>-->
<!--			</exclusions>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>net.sf.ehcache</groupId>-->
<!--			<artifactId>ehcache</artifactId>-->
<!--			<version>${ehcache.version}</version>-->
<!--			<exclusions>-->
<!--				<exclusion>-->
<!--					<groupId>org.slf4j</groupId>-->
<!--					<artifactId>slf4j-api</artifactId>-->
<!--				</exclusion>-->
<!--			</exclusions>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.apache.poi</groupId>-->
<!--			<artifactId>poi</artifactId>-->
<!--			<version>${poi.version}</version>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.slf4j</groupId>-->
<!--			<artifactId>slf4j-api</artifactId>-->
<!--			<version>${slf4j.version}</version>-->
<!--			<scope>provided</scope>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.slf4j</groupId>-->
<!--			<artifactId>jul-to-slf4j</artifactId>-->
<!--			<version>${slf4j.version}</version>-->
<!--			<scope>provided</scope>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>javax.ejb</groupId>-->
<!--			<artifactId>ejb-api</artifactId>-->
<!--			<version>3.0</version>-->
<!--			<scope>provided</scope>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>javax.annotation</groupId>-->
<!--			<artifactId>jsr250-api</artifactId>-->
<!--			<version>1.0</version>-->
<!--			<scope>provided</scope>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.jboss.ws</groupId>-->
<!--			<artifactId>jbossws-spi</artifactId>-->
<!--			<version>1.1.2.GA</version>-->
<!--			<scope>provided</scope>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>jboss</groupId>-->
<!--			<artifactId>jboss-annotations-ejb3</artifactId>-->
<!--			<version>4.2.2.GA</version>-->
<!--			<scope>provided</scope>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>jboss</groupId>-->
<!--			<artifactId>jbosssx-client</artifactId>-->
<!--			<version>4.2.2.GA</version>-->
<!--			<scope>provided</scope>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.apache.cxf</groupId>-->
<!--			<artifactId>cxf-api</artifactId>-->
<!--			<version>${cxf.version}</version>-->
<!--			<scope>provided</scope>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>org.jeasy</groupId>-->
<!--			<artifactId>easy-rules-support</artifactId>-->
<!--			<version>3.4.0</version>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>com.fasterxml.jackson.dataformat</groupId>-->
<!--			<artifactId>jackson-dataformat-xml</artifactId>-->
<!--			<version>${jackson.version}</version>-->
<!--		</dependency>-->

<!--		<dependency>-->
<!--			<groupId>apache-xerces</groupId>-->
<!--			<artifactId>xercesImpl</artifactId>-->
<!--			<version>2.9.1</version>-->
<!--			<scope>test</scope>-->
<!--		</dependency>-->
<!--        <dependency>-->
<!--            <groupId>io.dropwizard.metrics</groupId>-->
<!--            <artifactId>metrics-core</artifactId>-->
<!--            <version>3.2.6</version>-->
<!--            <exclusions>-->
<!--                <exclusion>-->
<!--                    <artifactId>slf4j-api</artifactId>-->
<!--                    <groupId>org.slf4j</groupId>-->
<!--                </exclusion>-->
<!--            </exclusions> &lt;!&ndash; versió compatible amb Java 7 &ndash;&gt;-->
<!--        </dependency>-->
    </dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-ejb-plugin</artifactId>
				<version>2.3</version>
				<configuration>
					<ejbVersion>3.0</ejbVersion>
				</configuration>
			</plugin>
		</plugins>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>false</filtering>
				<excludes>
					<exclude>**/version.properties</exclude>
				</excludes>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
				<includes>
					<include>**/version.properties</include>
				</includes>
			</resource>
		</resources>
	</build>
	<repositories>
		<repository>
			<id>jboss</id>
			<url>https://repository.jboss.org/nexus/content/groups/public-jboss/</url>
		</repository>
		<repository>
			<id>github-governib-maven-repos</id>
			<name>GovernIB Maven Repository</name>
			<url>https://governib.github.io/maven/maven/</url>
		</repository>
	</repositories>
</project>
