<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="DatosEspecificos" type="DatosEspecificos"/>
	<xs:complexType name="DatosEspecificos">
		<xs:choice>
			<xs:element ref="Consulta">
				<xs:annotation>
					<xs:documentation>Solo en el mensaje PETICION</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element ref="Retorno">
				<xs:annotation>
					<xs:documentation>Solo en el mensaje RESPUESTA</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:choice>
		<xs:attribute name="Id" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:element name="Consulta" type="Consulta"/>
	<xs:complexType name="Consulta">
		<xs:sequence>
			<xs:element ref="IDSolicitud"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Retorno" type="Retorno"/>
	<xs:complexType name="Retorno">
		<xs:sequence>
			<xs:element ref="Estado"/>
			<xs:element ref="Solicitud" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Solicitud">
		<xs:complexType>
			<xs:all>
				<xs:element ref="IdPeticionSIRAJ" minOccurs="0"/>
				<xs:element ref="NumPeticion" minOccurs="0"/>
				<xs:element name="FechaTraspaso" type="Fecha" minOccurs="0"/>
				<xs:element ref="TipoInformacion" minOccurs="0"/>
				<xs:element ref="TipoIdentidad" minOccurs="0"/>
				<xs:element ref="TipoPeticionario" minOccurs="0"/>
				<xs:element ref="IdRetorno" minOccurs="0"/>
				<xs:element ref="NombrePadre" minOccurs="0"/>
				<xs:element ref="NombreMadre" minOccurs="0"/>
				<xs:element ref="Email" minOccurs="0"/>
				<xs:element ref="Telefono" minOccurs="0"/>
				<xs:element ref="OrganoResolutor" minOccurs="0"/>
				<xs:element ref="NIP" minOccurs="0"/>
				<xs:element name="FechaResolucion" type="Fecha" minOccurs="0"/>
				<xs:element ref="TipoRespuestaAsincrona" minOccurs="0"/>
				<xs:element name="FechaNotificacionInteresado" type="Fecha" minOccurs="0"/>
				<xs:element name="CSV" type="xs:string" minOccurs="0"/>
				<xs:element name="CSVApostillado" type="xs:string" minOccurs="0"/>
				<xs:element name="URLVerificacion" type="xs:string" minOccurs="0"/>
				<xs:element ref="Nacimiento" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="IDSolicitud">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="40"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="IdPeticionSIRAJ">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="14"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="NumPeticion">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="7"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:simpleType name="Fecha">
		<xs:restriction base="xs:date"/>
	</xs:simpleType>
	<xs:element name="TipoInformacion">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="TipoIdentidad">
		<xs:simpleType>
			<xs:restriction base="xs:int">
				<xs:enumeration value="1"/>
				<xs:enumeration value="2"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="TipoPeticionario">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="3"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="IdRetorno">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="3"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Pais">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{3}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Provincia">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{2}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoPoblacion">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{5}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="NombrePadre">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="100"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="NombreMadre">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="100"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Email">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="70"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Telefono">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="15"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="OrganoResolutor">
		<xs:simpleType>
			<xs:restriction base="xs:string"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="TipoRespuestaAsincrona">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="15"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Estado">
		<xs:complexType>
			<xs:all>
				<xs:element ref="CodigoEstado"/>
				<xs:element ref="CodigoEstadoSecundario" minOccurs="0"/>
				<xs:element ref="LiteralError"/>
				<xs:element ref="LiteralErrorSecundario" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="CodigoEstado">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="4"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="LiteralError">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="1024"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoEstadoSecundario">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="16"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="LiteralErrorSecundario">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="1024"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="NIP">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:pattern value="\d{14}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="URLVerificacion">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="250"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Nacimiento">
		<xs:complexType>
			<xs:all>
				<xs:element ref="Pais" minOccurs="0"/>
				<xs:element ref="Provincia" minOccurs="0"/>
				<xs:element ref="CodigoPoblacion" minOccurs="0"/>
				<xs:element name="Fecha" type="FechaUnion" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="FechaUnion">
		<xs:union memberTypes="FechaNacimiento MesNacimiento AnioNacimiento"/>
	</xs:simpleType>
	<xs:simpleType name="FechaNacimiento">
		<xs:restriction base="xs:date"/>
	</xs:simpleType>
	<xs:simpleType name="MesNacimiento">
		<xs:restriction base="xs:gYearMonth"/>
	</xs:simpleType>
	<xs:simpleType name="AnioNacimiento">
		<xs:restriction base="xs:gYear"/>
	</xs:simpleType>
</xs:schema>
