package es.caib.pinbal.client.procediments;

public enum ClaseTramite {
    RECURSOS_HUMANOS,
    TRIBUTARIO,
    SANCIONADOR,
    AFILIACION_COTIZACION_SS,
    AUTORIZ_LICEN_CONCES_HOMOLOG,
    AYUDAS_BECAS_SUBVEN,
    CERTIFICADOS,
    CONTRATACION_PUB,
    CONVENIOS_COMUNIC,
    GESTION_ECON_PATRIM,
    DECLARAC_COMUNIC_INTERESADOS,
    INSPECTORA,
    PREMIOS,
    PRESTACIONES,
    REGISTROS_CENSOS,
    RESP_PATRIM_INDEM,
    REVISION_ACTOS_ADM_RECURSOS,
    SUGEREN_QUEJAS_CIUDADANOS,
    ADUANERO
}
