CREATE INDEX PBL_CORETRA_IDPETICION_I ON CORE_TRANSMISION(IDPETICION);
CREATE INDEX PBL_COREPETRES_IDPETICION_I ON CORE_PETICION_RESPUESTA(IDPETICION);

CREATE INDEX PBL_CONSULTA_MULT_I ON PBL_CONSULTA(CREATEDBY_CODI, ESTAT, MULTIPLE);
