alter table pbl_servei_config add unitat_dir3 varchar2(10);

CREATE INDEX PBL_CORETRA_IDPETICION_I ON CORE_TRANSMISION(IDPETICION);
CREATE INDEX PBL_COREPETRES_IDPETICION_I ON CORE_PETICION_RESPUESTA(IDPETICION);

CREATE INDEX PBL_CONSULTA_MULT_I ON PBL_CONSULTA(CREATEDBY_CODI, ESTAT, MULTIPLE);

CREATE INDEX PBL_CONSULTA_PARE_I ON PBL_CONSULTA(PARE_ID);
CREATE INDEX PBL_CONSULTA_PROCSERV_I ON PBL_CONSULTA(PROCSERV_ID);
CREATE INDEX PBL_PROCEDIMENT_ENTITAT_I ON PBL_PROCEDIMENT(ENTITAT_ID);
CREATE INDEX PBL_PROCSERV_PROCEDIMENT_I ON PBL_PROCEDIMENT_SERVEI(PROCEDIMENT_ID);
