--------------------------------------------------------
--  Configuracion de esquema scsp requirente 
--------------------------------------------------------

--------------------------------------------------------
--  Inserts for Table CORE_PARAMETRO_CONFIGURACION
--	Se deben sustituir los valores puestos a null por los valores reales de cada configuración
--	Consulte el documento del modelo de datos y el de configuración para ver que valores puede tomar cada parámetro
-------------------------------------------------------- 
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('nivelTraza','DEBUG','Nivel de traza a mostrar en los logs');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('pathLogs',null,'Ruta del fichero donde guardaremos los logs');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('logDinamico.enabled',null,'Parámetro que indica si se cargará de BBDD la configuración de logs o de fichero');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('core_log.enabled',null,'Parámetro que indica si se guardarán trazas en CORE_LOG de los errores ocurridos');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('imagen.logo','logo.jpg','Indica la imagen utilizada en los justificantes PDF');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('almacenamiento.ficheros',null,'Directorio donde se guardan los ficheros de las peticiones');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('almacenamiento.transmisiones',1,'Parámetro que indica si se guardarán los nodos de las transmisiones');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('keystoreFile',null,'Ruta del fichero keystore');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('keystoreType','jks','Tipo de keystore');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('keystorePass',null,'Password del keystore');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('afirma.enabled','true','Parámetro que indica si @Firma está activo');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('afirma.idAplicacion',null,'Id de aplicación para enviar a @Firma');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('afirma.url','https://des-afirma.redsara.es/afirmaws/services/ValidarCertificado','URL de @Firma');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('afirma.modoValidacion',2,'Modo de validación del certificado con @Firma');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('afirma.autenticacion.aliasSignerCert',null,'Alias del certificado con el que firmamos la peticiones para @Firma');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('custom.cert.validation.class','none','Clase propia de validación de certificados');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('periodo.validacion.certificados',24,'Periodo de validez del certificado en caché');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('tipoId','long','Longitud del identificador de la petición');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('prefijo.idpeticion',null,'Prefijo utilizado para la generación del id de petición');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('axis2.client.xml','/axis2/axis2.xml','Dirección relativa del archivo axis2.xml');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('axis2.client.repository','/axis2/','Path donde se encuentra el archivo axis2.xml');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('polling.enabled','true','Valor que indica si el Polling estará o no activado');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('task.polling.espera',5,'Valor que indica el tiempoq ue tardará el Polling en ser ejecutado por primera vez.Se expresa en minutos.');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('task.polling.intervalo',1440,'valor que indica el tiempo de ejecución del Polling');
INSERT INTO CORE_PARAMETRO_CONFIGURACION (NOMBRE,VALOR,DESCRIPCION) VALUES ('version.datamodel.scsp','3.5.3','Especifica la versión del modelo de datos actual');


--------------------------------------------------------
--  Inserts for Table organismo_cesionario
-- Se debe modificar según necesidades y según los datos propios del organismo
--------------------------------------------------------
INSERT INTO organismo_cesionario (id,nombre, cif, fechaalta,bloqueado, logo) VALUES ((ID_ORGANISMO_CESIONARIO_SEQ.nextval),NULL,NULL,SYSDATE,'0',NULL);

--------------------------------------------------------
--  Inserts for Table CORE_CLAVE_PRIVADA
-- Se debe modificar según necesidades y según la configuración del almacén de claves utilizado
--------------------------------------------------------
INSERT INTO CORE_CLAVE_PRIVADA (id,ALIAS,NOMBRE,PASSWORD,NUMEROSERIE,ORGANISMO,FECHAALTA) VALUES ((ID_CLAVE_PRIVADA_SEQUENCE.nextval),null,null,null,null,(ID_ORGANISMO_CESIONARIO_SEQ.currval),SYSDATE);

--------------------------------------------------------
--  Inserts for Table CORE_CLAVE_PUBLICA
-- Se debe modificar según necesidades y según la configuración del almacén de claves utilizado
--------------------------------------------------------
INSERT INTO CORE_CLAVE_PUBLICA (ALIAS,NOMBRE,NUMEROSERIE) VALUES (null,null,null);

--------------------------------------------------------
--  Inserts for Table CORE_EMISOR_CERTIFICADO
-- Se deben eliminar los inserts correspondientes a organismos de los que no vamos a consumir servicios
--------------------------------------------------------

INSERT INTO CORE_EMISOR_CERTIFICADO (CIF,NOMBRE) VALUES ('S2826053G','Catastro');
INSERT INTO CORE_EMISOR_CERTIFICADO (CIF,NOMBRE) VALUES ('Q2819009H','SPEE-INEM');
INSERT INTO CORE_EMISOR_CERTIFICADO (CIF,NOMBRE) VALUES ('Q2827003A','TGSS');
INSERT INTO CORE_EMISOR_CERTIFICADO (CIF,NOMBRE) VALUES ('Q2826000H','AEAT');
INSERT INTO CORE_EMISOR_CERTIFICADO (CIF,NOMBRE) VALUES ('S2818001F','Educacion');
INSERT INTO CORE_EMISOR_CERTIFICADO (CIF,NOMBRE) VALUES ('S2833002E','MINHAP');
INSERT INTO CORE_EMISOR_CERTIFICADO (CIF,NOMBRE) VALUES ('Q2827004I','IMSERSO');
INSERT INTO CORE_EMISOR_CERTIFICADO (CIF,NOMBRE) VALUES ('Q2827002C','INSS');
INSERT INTO CORE_EMISOR_CERTIFICADO (CIF,NOMBRE) VALUES ('S2813001A','RRCC Justicia');
INSERT INTO CORE_EMISOR_CERTIFICADO (CIF,NOMBRE) VALUES ('S2826013A','DG. Seguros');
INSERT INTO CORE_EMISOR_CERTIFICADO (CIF,NOMBRE) VALUES ('S3100000C','Gobierno de Navarra');
INSERT INTO CORE_EMISOR_CERTIFICADO (CIF,NOMBRE) VALUES ('S2812001B','MAEC');
INSERT INTO CORE_EMISOR_CERTIFICADO (CIF,NOMBRE) VALUES ('Q2826039F','INE');
INSERT INTO CORE_EMISOR_CERTIFICADO (CIF,NOMBRE) VALUES ('S2816015H','DGP');
INSERT INTO CORE_EMISOR_CERTIFICADO (CIF,NOMBRE) VALUES ('Q2863008E','C.G.Notariado');

--------------------------------------------------------
--  Inserts for Table CORE_SERVICIO
-- Se deben eliminar los inserts correspondientes a los servicios que no vamos a consumir
-- Vienen preconfigurados los servicios de la plataforma de intermediación para pre producción
-- Antes de ejecutar los inserts se debe de modificar PREFIJO-PETICION y (ID_CLAVE_PRIVADA_SEQUENCE.currval)
--------------------------------------------------------

INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDSPEESITWS01','https://intermediacionpp.redsara.es/SPEE-INEM/services/CertificadoDatosDesempleo','https://intermediacionpp.redsara.es/SPEE-INEM/services/CertificadoDatosDesempleoAsincrona','PeticionSincrona','peticionAsincrona','solicitudRespuesta','V2','XMLSignature','PREFIJO-PETICION',NULL,NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Situación de Desempleo','Q2819009H',(SYSDATE),NULL,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,'/plantillaspdf/sepe/plantilla_SituacionDesempleo_SVDPEESITWS01_pdf.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDSPEEIACTWS01','https://intermediacionpp.redsara.es/SPEE-INEM/services/CertificadoImportesActuales','https://intermediacionpp.redsara.es/SPEE-INEM/services/CertificadoImportesActualesAsincrona','PeticionSincrona','peticionAsincrona','solicitudRespuesta','V2','XMLSignature','PREFIJO-PETICION',NULL,NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Importes de prestación de desempleo percibidos a fecha actual','Q2819009H',(SYSDATE),NULL,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,'/plantillaspdf/sepe/plantilla_PrestacionFechaActual_SVDSPEEIACTWS01_pdf.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDSPEEIPERWS01','https://intermediacionpp.redsara.es/SPEE-INEM/services/CertificadoImportesPeriodos','https://intermediacionpp.redsara.es/SPEE-INEM/services/CertificadoImportesPeriodosAsincrona','PeticionSincrona','peticionAsincrona','solicitudRespuesta','V2','XMLSignature','PREFIJO-PETICION',NULL,NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Importes de prestación de desempleo percibidos en un periodo','Q2819009H',(SYSDATE),NULL,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,'/plantillaspdf/sepe/plantilla_PrestacionPeriodo_SVDSPEEIPERWS01_pdf.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDSEPEDEMWS01','https://intermediacionpp.redsara.es/SPEE-INEM/services/InscritoDemandanteEmpleo','https://intermediacionpp.redsara.es/SPEE-INEM/services/InscritoDemandanteEmpleoAsincrona','PeticionSincrona','peticionAsincrona','solicitudRespuesta','V3','XMLSignature','PREFIJO-PETICION',NULL,NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Servicio Consulta Demandante Empleo a Fecha Actual','Q2819009H',(SYSDATE),NULL,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,'/plantillaspdf/sepe/plantilla_DemandanteEmpleoFechaActual_SVDSEPEDEMWS01_pdf.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDSEPEDEMFECHAWS01','https://intermediacionpp.redsara.es/SPEE-INEM/services/InscritoDemandanteEmpleoFechaConcreta','https://intermediacionpp.redsara.es/SPEE-INEM/services/InscritoDemandanteEmpleoFechaConcretaAsincrona','PeticionSincrona','peticionAsincrona','solicitudRespuesta','V3','XMLSignature','PREFIJO-PETICION',NULL,NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Servicio Consulta Demandante Empleo en Fecha Concreta','Q2819009H',(SYSDATE),NULL,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,'/plantillaspdf/sepe/plantilla_DemandanteEmpleoFechaConcreta_SVDSEPEDEMFECHAWS01_pdf.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDCDATWS01','https://intermediacionpp.redsara.es/Catastro/services/ConsultaDatos','https://intermediacionpp.redsara.es/Catastro/services/ConsultaDatos','PeticionSincrona','PeticionAsincrona','SolicitudRespuesta','V2','XMLSignature','PREFIJO-PETICION',NULL,NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Consulta de datos catastrales','S2826053G',(SYSDATE),NULL,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,'/plantillaspdf/catastro/plantilla_ConsultaDatosCatastro_SVDCDATWS01.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDCTITWS01','https://intermediacionpp.redsara.es/Catastro/services/CertificacionTitular','https://intermediacionpp.redsara.es/Catastro/services/CertificacionTitular','PeticionSincrona','PeticionAsincrona','SolicitudRespuesta','V2','XMLSignature','PREFIJO-PETICION',NULL,NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Certificación de titularidad catastral','S2826053G',(SYSDATE),NULL,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,null);
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDCDYGWS01','https://intermediacionpp.redsara.es/Catastro/services/ObtenerDescriptivaYGrafica','https://intermediacionpp.redsara.es/Catastro/services/ObtenerDescriptivaYGrafica','PeticionSincrona','PeticionAsincrona','SolicitudRespuesta','V2','XMLSignature','PREFIJO-PETICION',NULL,NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Certificación Descriptiva y Gráfica de un Inmueble','S2826053G',(SYSDATE),NULL,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,null);
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDCBIWS01','https://intermediacionpp.redsara.es/Catastro/services/BienesInmuebles','https://intermediacionpp.redsara.es/Catastro/services/BienesInmuebles','PeticionSincrona','PeticionAsincrona','SolicitudRespuesta','V2','XMLSignature','PREFIJO-PETICION',NULL,NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Consulta de Bienes Inmuebles','S2826053G',(SYSDATE),NULL,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,'/plantillaspdf/catastro/plantilla_ConsultaBienesInmuebles_SVDCBIWS01.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('Q2827003ATGSS001','https://intermediacionpp.redsara.es/TGSS/services/CorrientePago','https://intermediacionpp.redsara.es/TGSS/services/CorrientePagoAsincrono','PeticionSincrona','Solicitar','SolicitarRespuesta','V3','WS-Security','PREFIJO-PETICION','//*[local-name()=''DatosEspecificos'']',NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Estar al corriente de Pago con la Seguridad Social','Q2827003A',(SYSDATE),NULL,0,'//*[local-name()=''Descripcion'']','//*[local-name()=''Codigo'']',60,null,'/plantillaspdf/tgss/plantilla_CorrientePagoSegSocial_Q2827003ATGSS001.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('Q2827003ATGSS006','https://intermediacionpp.redsara.es/TGSS/services/AltaEnFecha',NULL,'PeticionSincrona',NULL,NULL,'V3','WS-Security','PREFIJO-PETICION','//*[local-name()=''DatosEspecificos'']',NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Situaciún laboral en fecha concreta','Q2827003A',SYSDATE,NULL,0,'//*[local-name()=''Descripcion'']','//*[local-name()=''Codigo'']',60,null,'/plantillaspdf/tgss/plantilla_SituacionLaboralFechaConcreta_Q2827003ATGSS006.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('AEAT101I','https://intermediacionpp.redsara.es/AEAT/services/CorrientePago',NULL,'SolicitudTransmisionOper',NULL,NULL,'V3','WS-Security','PREFIJO-PETICION','//*[local-name()=''DatosEspecificos'']',NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Estar al Corriente de las Obligaciones Tributarias según Ley de Contratos','Q2826000H',(SYSDATE),NULL,0,'//*[local-name()=''DescRespuesta'']','//*[local-name()=''CodRespuesta'']',60,null,'/plantillaspdf/aeat/plantilla_CorrientePagoObligacionesContratos_AEAT101I.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('AEAT102I','https://intermediacionpp.redsara.es/AEAT/services/CorrientePago',NULL,'SolicitudTransmisionOper',NULL,NULL,'V3','WS-Security','PREFIJO-PETICION','//*[local-name()=''DatosEspecificos'']',NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Estar al Corriente de las Obligaciones Tributarias para Autorización de Transporte','Q2826000H',(SYSDATE),NULL,0,'//*[local-name()=''DescRespuesta'']','//*[local-name()=''CodRespuesta'']',60,null,'/plantillaspdf/aeat/plantilla_CorrientePagoObligacionesTransportes_AEAT102I.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('AEAT103I','https://intermediacionpp.redsara.es/AEAT/services/CorrientePago',NULL,'PeticionSincrona',NULL,NULL,'V3','WS-Security','PREFIJO-PETICION','//*[local-name()=''DatosEspecificos'']',NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Estar al Corriente de las Obligaciones Tributarias para Subvenciones y Ayudas','Q2826000H',(SYSDATE),NULL,0,'//*[local-name()=''DescRespuesta'']','//*[local-name()=''CodRespuesta'']',60,null,'/plantillaspdf/aeat/plantilla_CorrientePagoObligacionesSubvenciones_AEAT103I.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('AEAT104I','https://intermediacionpp.redsara.es/AEAT/services/CorrientePago',NULL,'SolicitudTransmisionOper',NULL,NULL,'V3','WS-Security','PREFIJO-PETICION','//*[local-name()=''DatosEspecificos'']',NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Estar al Corriente de las Obligaciones Tributarias para Permisos de Residencia y Trabajo','Q2826000H',(SYSDATE),NULL,0,'//*[local-name()=''DescRespuesta'']','//*[local-name()=''CodRespuesta'']',60,null,'/plantillaspdf/aeat/plantilla_CorrientePagoObligacionesPermisosRes_AEAT104I.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('MAP01WS01',NULL,'https://domiciliopp.redsara.es/mapWebService/services/ComunicacionDomicilio',NULL,'peticionAsincrona','solicitudRespuesta','V2','XMLSignature','PREFIJO-PETICION',NULL,NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Comunicaciún de Cambio de domicilio','S2833002E',SYSDATE,NULL,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,null);
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('CDISFWS01','https://intermediacionpp.redsara.es/peticionSVDI/services/ConsultaIdentidad','https://intermediacionpp.redsara.es/peticionSVDI/services/ConsultaIdentidadAsincrona','realizaPeticion','peticionAsincrona','solicitudRespuesta','V2','XMLSignature','PREFIJO-PETICION',NULL,NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Consulta datos de identidad','S2816015H',(SYSDATE),NULL,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,'/plantillaspdf/minhap/plantilla_ConsultaDatosIdentidad_CDISFWS01_pdf.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('VDISFWS01','https://intermediacionpp.redsara.es/peticionSVDI/services/VerificacionIdentidad','https://intermediacionpp.redsara.es/peticionSVDI/services/VerificacionIdentidadAsincrona','realizaPeticion','peticionAsincrona','solicitudRespuesta','V2','XMLSignature','PREFIJO-PETICION',NULL,NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Verificación de datos de identidad','S2816015H',(SYSDATE),NULL,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,'/plantillaspdf/minhap/plantilla_VerificacionIdentidad_VDISFWS01_pdf.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('VDRSFWS02','https://intermediacionpp.redsara.es/peticionSVDRExt/services/VerificacionResidencia','https://intermediacionpp.redsara.es/peticionSVDRExt/services/VerificacionResidenciaAsincrona','realizaPeticion','peticionAsincrona','solicitudRespuesta','V2','XMLSignature','PREFIJO-PETICION',NULL,NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Verificación de Datos de Residencia (extendida)','Q2826039F',(SYSDATE),NULL,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,'/plantillaspdf/minhap/plantilla_VerificacionResidenciaExtendida_VDRSFWS02_pdf.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDREXTFECHAWS01','https://intermediacionpp.redsara.es/peticionSVDRExt/services/VerificacionResidenciaFecha','https://intermediacionpp.redsara.es/peticionSVDRExt/services/VerificacionResidenciaFechaAsincrona','peticionSincrona','peticionAsincrona','solicitudRespuesta','V3','WS-Security','PREFIJO-PETICION',NULL,NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Verificación de Datos de Residencia Con Fecha de última Variación','Q2826039F',(SYSDATE),NULL,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,NULL,'/plantillaspdf/minhap/plantilla_ServicioConsultaResidenciaFecha_SVDREXTFECHAWS01.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDRWS01','https://intermediacionpp.redsara.es/peticionSVDR/services/VerificacionResidencia','https://intermediacionpp.redsara.es/peticionSVDR/services/VerificacionResidenciaAsincrona','peticionSincrona','peticionAsincrona','solicitudRespuesta','V3','XMLSignature','PREFIJO-PETICION',NULL,NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Verificación de Datos de Residencia de ámbito Territorial','Q2826039F',(SYSDATE),NULL,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,NULL,'/plantillaspdf/minhap/plantilla_ServicioConsultaResidenciaTerritorial_SVDRWS01.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDTUWS01','https://intermediacionpp.redsara.es/Educacion/services/TitulosUniversitarios','https://intermediacionpp.redsara.es/Educacion/services/TitulosUniversitariosAsincrona','realizaPeticion','peticionAsincrona','solicitudRespuesta','V2','XMLSignature','PREFIJO-PETICION',NULL,NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Titulos universitarios','S2818001F',(SYSDATE),NULL,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,'/plantillaspdf/educacion/plantilla_sctu_SVDTUWS01_pdf.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDTNUWS01','https://intermediacionpp.redsara.es/Educacion/services/TitulosNoUniversitarios','https://intermediacionpp.redsara.es/Educacion/services/TitulosNoUniversitariosAsincrona','realizaPeticion','peticionAsincrona','solicitudRespuesta','V2','XMLSignature','PREFIJO-PETICION',NULL,NULL,NULL,(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Titulos no universitarios','S2818001F',(SYSDATE),NULL,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,'/plantillaspdf/educacion/plantilla_sctnu_SVDTNUWS01_pdf.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('AEATIAE','https://ws.ia.aeat.es/es13/S/IAE1ADWSIAE1',NULL,'operacion_servicio',NULL,NULL,'V3','XMLSignature','PREFIJO-PETICION',NULL,NULL,'/schemas/AEATIAEv3',(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Impuesto Actividades Economicas','Q2826000H',SYSDATE,NULL,0,'//*[local-name()=''DescRespuesta'']','//*[local-name()=''CodRespuesta'']',60,null,'/plantillaspdf/aeat/plantilla_ImpuestoActividadesEconomicas_AEATIAE_pdf.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('AEATIAEA','https://ws.ia.aeat.es/ES98/L/iniinvoc/es.aeat.dit.adu.suap.iaews.IAEV3SOAP',null,'operacion_servicio',null,null,'V3','XMLSignature','PREFIJO-PETICION',null,null,'/schemas/AEATIAEv3',(ID_CLAVE_PRIVADA_SEQUENCE.currval),null,null,0,0,null,'Impuesto Actividades Economicas','Q2826000H',(SYSDATE),null,0,'//*[local-name()=''DescRespuesta'']','//*[local-name()=''CodRespuesta'']',60,null,'/plantillaspdf/aeat/plantilla_ImpuestoActividadesEconomicas_AEATIAE_pdf.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('AEATIR01','https://ws.ia.aeat.es/ES98/L/iniinvoc/es.aeat.dit.adu.suap.irpfws.IRPFV3SOAP',NULL,'operacion_servicio',NULL,NULL,'V3','XMLSignature','PREFIJO-PETICION',NULL,NULL,'/schemas/AEATIR01v3',(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Certificado de Renta','Q2826000H',(SYSDATE),NULL,0,'//*[local-name()=''DescRespuesta'']','//*[local-name()=''CodRespuesta'']',60,null,'/plantillaspdf/aeat/plantilla_ConsultaRenta_AEATIR01.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SCPWIJ1R','https://ws.ia.aeat.es/es13/S/SCPWSCPWIJ1R',NULL,'operacion_servicio',NULL,NULL,'DomicilioFiscalV2','XMLSignature','PREFIJO-PETICION',NULL,NULL,'/schemas/SCPWIJ1Rv2',(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Domicilio Fiscal','Q2826000H',(SYSDATE),NULL,0,'//*[local-name()=''DescRespuesta'']','//*[local-name()=''CodRespuesta'']',60,null,'/plantillaspdf/aeat/plantilla_DomicilioFiscal_SCPWIJ1R.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('DOMFISC','https://ws.ia.aeat.es/ES98/L/iniinvoc/es.aeat.dit.adu.suap.domicilioWS.DomFV3SOAP',NULL,'operacion_servicio',NULL,NULL,'V3','XMLSignature','PREFIJO-PETICION',NULL,NULL,'/schemas/DOMFISCv3','ID-CERTIFICADO-FIRMA',NULL,NULL,0,0,NULL,'Domicilio Fiscal v3','Q2826000H',CURRENT_TIMESTAMP,NULL,0,'//*[local-name()=''DescRespuesta'']','//*[local-name()=''CodRespuesta'']',60,null,'/plantillaspdf/aeat/plantilla_DomicilioFiscal_DOMFISC.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDCDEPENWS01','https://intermediacionpp.redsara.es/IMSERSO/services/ConsultaDatosDependencia','https://intermediacionpp.redsara.es/IMSERSO/services/ConsultaDatosDependenciaAsincrona','peticionSincrona','peticionAsincrona','solicitudRespuesta','V3','WS-Security','PREFIJO-PETICION',NULL,NULL,'/schemas/SVDCDEPENWS01v3',(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Consulta del nivel y grado de dependencia','Q2827004I',(SYSDATE),NULL,10,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,'/plantillaspdf/imserso/plantilla_ServicioConsultaDependencia_SVDCDEPENWS01.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('Q2827002CINSS001','https://intermediacionpp.redsara.es/INSS/services/ConsultaPrestaciones',NULL,'peticionSincrona','peticionAsincrona','solicitudRespuesta','V3','WS-Security','PREFIJO-PETICION',NULL,NULL,'/schemas/Q2827002CINSS001v3',(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Consulta de las prestaciones del Registro de Prestaciones Sociales P�blicas, Incapacidad Temporal y Maternidad','Q2827002C',(SYSDATE),NULL,10,'//*[local-name()=''Descripcion'']','//*[local-name()=''Codigo'']',60,null,'/plantillaspdf/inss/plantilla_ConsultaPrestacionesSociales_Q2827002CINSS001.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('DGSFP0001','https://intermediacionpp.redsara.es/DG_Seguros/services/ConsultaMediadores','https://intermediacionpp.redsara.es/DG_Seguros/services/ConsultaMediadoresAsincrona','peticionSincrona','peticionAsincrona','solicitudRespuesta','V3','WS-Security','PREFIJO-PETICICION',NULL,NULL,'/schemas/DGSFP0001v3',(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Consulta de Mediadores de Seguros y Reaseguros','S2826013A',(SYSDATE),NULL,10,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,'/plantillaspdf/seguros/plantilla_Seguros.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('DGSFP0002','https://intermediacionpp.redsara.es/DG_Seguros/services/ConsultaAseguradoras','https://intermediacionpp.redsara.es/DG_Seguros/services/ConsultaAseguradorasAsincrona','peticionSincrona','peticionAsincrona','solicitudRespuesta','V3','WS-Security','PREFIJO-PETICICION',NULL,NULL,'/schemas/DGSFP0002v3',(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Consulta de Aseguradoras y Reaseguradoras','S2826013A',(SYSDATE),NULL,10,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,'/plantillaspdf/seguros/plantilla_Seguros.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('DGSFP0003','https://intermediacionpp.redsara.es/DG_Seguros/services/ConsultaFondos','https://intermediacionpp.redsara.es/DG_Seguros/services/ConsultaFondosAsincrona','peticionSincrona','peticionAsincrona','solicitudRespuesta','V3','WS-Security','PREFIJO-PETICICION',NULL,NULL,'/schemas/DGSFP0003v3',(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Consulta de Planes y Fondos de pensiones','S2826013A',(SYSDATE),NULL,10,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,'/plantillaspdf/seguros/plantilla_Seguros.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('DGSFP0005',NULL,'https://intermediacionpp.redsara.es/DG_Seguros/services/ConsultaSolvenciaAsincrona',NULL,'peticionAsincrona','solicitudRespuesta','V3','WS-Security','PREFIJO-PETICICION',NULL,NULL,'/schemas/DGSFP0005v3',(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Consulta de Solvencia','S2826013A',(SYSDATE),NULL,10,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,'/plantillaspdf/seguros/plantilla_Seguros.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDSCCMWS01','https://intermediacionpp.redsara.es/RegCivil/services/ConsultaMatrimonio','https://intermediacionpp.redsara.es/RegCivil/services/ConsultaMatrimonioAsincrona','peticionSincrona','peticionAsincrona','solicitudRespuesta','V3','WS-Security','PREFIJO-PETICICION',NULL,NULL,'/schemas/SVDSCCMWS01v3',(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Certificado de Matrimonio','S2813001A',(SYSDATE),NULL,10,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,'/plantillaspdf/justicia/plantilla_ConsultaMatrimonio_SVDSCCMWS01.xslt')		;
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDSCCNWS01','https://intermediacionpp.redsara.es/RegCivil/services/ConsultaNacimiento','https://intermediacionpp.redsara.es/RegCivil/services/ConsultaNacimientoAsincrona','peticionSincrona','peticionAsincrona','solicitudRespuesta','V3','WS-Security','PREFIJO-PETICICION',NULL,NULL,'/schemas/SVDSCCNWS01v3',(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Certificado de Matrimonio','S2813001A',(SYSDATE),NULL,10,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,'/plantillaspdf/justicia/plantilla_ConsultaNacimiento_SVDSCCNWS01.xslt')		;
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDSCCDWS01','https://intermediacionpp.redsara.es/RegCivil/services/ConsultaDefuncion','https://intermediacionpp.redsara.es/RegCivil/services/ConsultaDefuncionAsincrona','peticionSincrona','peticionAsincrona','solicitudRespuesta','V3','WS-Security','PREFIJO-PETICICION',NULL,NULL,'/schemas/SVDSCCNWS01v3',(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Certificado de Defunción','S2813001A',(SYSDATE),NULL,10,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,null,'/plantillaspdf/justicia/plantilla_ConsultaDefuncion_SVDSCCDWS01.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('HTNIAE','https://intermediacionpp.redsara.es/Navarra/services/ConsultaIAE','https://intermediacionpp.redsara.es/Navarra/services/ConsultaIAEAsincrona','PeticionSincrona',null,null,'V3','WS-Security','PREFIJO-PETICICION',null,null,'/schemas/HTNIAEv3',(ID_CLAVE_PRIVADA_SEQUENCE.currval),null,null,50,999,null,'Impuesto Actividades Económicas','S3100000C',(SYSDATE),null,10,'//*[local-name()=''DescRespuesta'']','//*[local-name()=''CodRespuesta'']',60,null,'/plantillaspdf/navarra/plantilla_ImpuestoActividadesEconomicas_HTNIAE.xslt');			
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('AEATIREA','https://ws.ia.aeat.es/ES98/L/iniinvoc/es.aeat.dit.adu.suap.ireaws.IREAV3SOAP',NULL,'realizaPeticion ',NULL,NULL,'V3','XMLSignature','PREFIJO-PETICION','//*[local-name()=''DatosEspecificos'']',NULL,'/schemas/AEATIREAv3',(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Servicio Consulta Renta Agraria V3','Q2826000H',(SYSDATE),NULL,0,'//*[local-name()=''DescRespuesta'']','//*[local-name()=''CodRespuesta'']',60,null,null);
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('AEATRDT1','https://ws.ia.aeat.es/es13/S/SCPWADWSRDT1',null,'PeticionSincrona',null,null,'V3','XMLSignature','PREFIJO',null,null,'/schemas/AEATRDT1v3',(ID_CLAVE_PRIVADA_SEQUENCE.currval),null,null,50,999,null,'Rendimientos Trabajo','Q2826000H',(SYSDATE),null,10,'//*[local-name()=''DescRespuesta'']','//*[local-name()=''CodRespuesta'']',60,null,'/plantillaspdf/aeat/plantilla_RendimientosTrabajo_AEATRDT1.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDRESLEGEXWS01','https://intermediacionpp.redsara.es/Extranjeria/services/ConsultaResidenciaLegal','https://intermediacionpp.redsara.es/Extranjeria/services/ConsultaResidenciaLegalAsincrona','PeticionSincrona','peticionAsincrona','solicitudRespuesta','V3','WS-Security',NULL,NULL,NULL,'/schemas/SVDRESLEGEXWS01v3',(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,50,999,NULL,'Verificacion de Datos de Residencia Legal (extranjeria)','S2833002E',(SYSDATE),NULL,10,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,NULL,'/plantillaspdf/minhap/plantilla_ConsultaDatosResidenciaLegal_SVDRESLEGEXWS01.xslt');
INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDMAECWS01','https://intermediacionpp.redsara.es/MAEC/services/ConsultaFirmas','https://intermediacionpp.redsara.es/MAEC/services/ConsultaFirmasAsincrona','peticionSincrona','peticionAsincrona','solicitudRespuesta','V3','WS-Security','Peiq',null,null,'/schemas/SVDMAECWS01v3',(ID_CLAVE_PRIVADA_SEQUENCE.currval),null,null,0,0,null,'Servicio Legalización Firmas','S2812001B',(SYSDATE),null,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,NULL,'/plantillaspdf/maec/plantilla_ServicioLegalizacionFirmas_SVDMAECWS01_pdf.xslt');


INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDNOTCOPSIMWS01','https://intermediacionpp.redsara.es/NOTARIOS/services/ConsultarCopiaSimple',NULL,'peticionSincrona',NULL,NULL,'V3','WS-Security','PREFIJO-PETICION',NULL,NULL,'/schemas/SVDNOTCOPSIMWS01v3',(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Consulta de copia simple','Q2863008E',(SYSDATE),NULL,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,NULL,'/plantillaspdf/notarios/plantilla_NotariosCopiaSimple_SVDNOTCOPSIMWS01.xslt');

INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDNOTLISTWS01','https://intermediacionpp.redsara.es/NOTARIOS/services/ConsultarNotarios',NULL,'peticionSincrona',NULL,NULL,'V3','WS-Security','PREFIJO-PETICION',NULL,NULL,'/schemas/SVDNOTLISTWS01v3',(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Lista de Notarios','Q2863008E',(SYSDATE),NULL,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,NULL,'/plantillaspdf/notarios/plantilla_NotariosLista_SVDNOTLISTWS01.xslt');

INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDNOTSUBADMWS01','https://intermediacionpp.redsara.es/NOTARIOS/services/ConsultarAdministradores',NULL,'peticionSincrona',NULL,NULL,'V3','WS-Security','PREFIJO-PETICION',NULL,NULL,'/schemas/SVDNOTSUBADMWS01v3',(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Consulta de subsistencia de administrador','Q2863008E',(SYSDATE),NULL,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,NULL,'/plantillaspdf/notarios/plantilla_NotariosAdministradores_SVDNOTSUBADMWS01.xslt');

INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDNOTSUBWS01','https://intermediacionpp.redsara.es/NOTARIOS/services/ConsultarSubsistencia',NULL,'peticionSincrona',NULL,NULL,'V3','WS-Security','PREFIJO-PETICION',NULL,NULL,'/schemas/SVDNOTSUBWS01v3',(ID_CLAVE_PRIVADA_SEQUENCE.currval),NULL,NULL,0,0,NULL,'Consulta de subsistencia de apoderamiento','Q2863008E',(SYSDATE),NULL,0,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,NULL,'/plantillaspdf/notarios/plantilla_NotariosSubsistencia_SVDNOTSUBWS01.xslt');


INSERT INTO core_servicio (id,codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ((SELECT ID_SERVICIO_SEQUENCE.nextval FROM DUAL),'NIVRENTI','https://intermediacionpp.redsara.es/servicios/SVD/AEAT.NivelDeRenta','','peticionSincrona','','','V3','WS-Security','',NULL,NULL,'/schemas/NIVRENTIv3',NULL,NULL,'',50,999,NULL,'Nivel de Renta Intermediado',(select id from core_emisor_certificado where cif='Q2826000H' and rownum<=1) ,(SYSDATE),NULL,10,'//*[local-name()=\'DescripcionError\']','//*[local-name()=\'CodRet\']',60,NULL,'/plantillaspdf/aeat/plantilla_NivelRenta_NIVRENTI_pdf.xslt');
INSERT INTO core_servicio (id,codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ((SELECT ID_SERVICIO_SEQUENCE.nextval FROM DUAL),'ECOT101I','https://intermediacionpp.redsara.es/servicios/SVD/AEAT.CorrientePagoContrataciones','','peticionSincrona','','','V3','WS-Security','',NULL,NULL,'/schemas/ECOT101Iv3',NULL,NULL,'',50,999,NULL,'Estar al Corriente de Pago de las Obligaciones Tributarias para Autorización de Transporte con indicación de incumplimientos',(select id from core_emisor_certificado where cif='Q2826000H' and rownum<=1),(SYSDATE),NULL,10,'//*[local-name()=''DescripcionError'']','//*[local-name()=''CodRet'']',60,NULL,'/plantillaspdf/aeat/plantilla_CorrientePago_ECOT101I.xslt');
INSERT INTO core_servicio (id,codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ((SELECT ID_SERVICIO_SEQUENCE.nextval FROM DUAL),'ECOT102I','https://intermediacionpp.redsara.es/servicios/SVD/AEAT.CorrientePagoTransportes',NULL,'peticionSincrona',NULL,NULL,'V3','WS-Security','',NULL,NULL,'/schemas/ECOT102Iv3',NULL,NULL,'',50,999,NULL,'Estar al Corriente de Pago de las Obligaciones Tributarias para Permisos de Residencia y Trabajo con indicación de incumplimientos',(select id from core_emisor_certificado where cif='Q2826000H' and rownum<=1),(SYSDATE),NULL,10,'//*[local-name()=''DescripcionError'']','//*[local-name()=''CodRet'']',60,NULL,'/plantillaspdf/aeat/plantilla_CorrientePago_ECOT102I.xslt');
INSERT INTO core_servicio (id,codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ((SELECT ID_SERVICIO_SEQUENCE.nextval FROM DUAL),'ECOT103I','https://intermediacionpp.redsara.es/servicios/SVD/AEAT.CorrientePagoAyudas',NULL,'peticionSincrona',NULL,NULL,'V3','WS-Security','',NULL,NULL,'/schemas/ECOT103Iv3',NULL,NULL,'',50,999,NULL,'Estar al Corriente de Pago de las Obligaciones Tributarias según Ley de Contratos con indicación de incumplimientos',(select id from core_emisor_certificado where cif='Q2826000H' and rownum<=1),(SYSDATE),NULL,10,'//*[local-name()=''DescripcionError'']','//*[local-name()=''CodRet'']',60,NULL,'/plantillaspdf/aeat/plantilla_CorrientePago_ECOT103I.xslt');
INSERT INTO core_servicio (id,codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ((SELECT ID_SERVICIO_SEQUENCE.nextval FROM DUAL),'ECOT104I','https://intermediacionpp.redsara.es/servicios/SVD/AEAT.CorrientePagoTrabajoExtranjeros',NULL,'peticionSincrona',NULL,NULL,'V3','WS-Security','',NULL,NULL,'/schemas/ECOT104Iv3',NULL,NULL,'',50,999,NULL,'Estar al Corriente de Pago de las Obligaciones Tributarias para Subvenciones y Ayudas con indicación de incumplimientos',(select id from core_emisor_certificado where cif='Q2826000H' and rownum<=1),(SYSDATE),NULL,10,'//*[local-name()=''DescripcionError'']','//*[local-name()=''CodRet'']',60,NULL,'/plantillaspdf/aeat/plantilla_CorrientePago_ECOT104I.xslt');


INSERT INTO core_servicio (codcertificado,urlsincrona,urlasincrona,actionsincrona,actionasincrona,actionsolicitud,versionesquema,tiposeguridad,prefijopeticion,xpathcifradosincrono,xpathcifradoasincrono,esquemas,clavefirma,clavecifrado,algoritmocifrado,numeromaximoreenvios,maxsolicitudespeticion,prefijoidtransmision,descripcion,emisor,fechaalta,fechabaja,caducidad,xpathliteralerror,xpathcodigoerror,timeout,validacionfirma,plantillaXSLT) VALUES ('SVDSCDWS01',NULL,'https://intermediacionpp.redsara.es/servicios/SVD/SCD.ComunicacionDomicilio',NULL,'peticionAsicrona','solicitudRespuesta','V3','WS-Security','',NULL,NULL,'/schemas/SVDSCDWS01v3',NULL,NULL,'',50,999,NULL,'Comunicación de Cambio de domicilio', (select id from core_emisor_certificado where cif='S2833002E' and rownum<=1),(SYSDATE),NULL,10,'//*[local-name()=''LiteralError'']','//*[local-name()=''CodigoEstado'']',60,NULL,'/plantillaspdf/minhap/plantilla_CambioDomicilio_SVDSCDWS01_pdf.xslt');

--------------------------------------------------------
--  Inserts for Table CORE_MODULO
-- Se debe modificar según necesidades los parámetros '1' Activado por defecto o '0' desactivado
--------------------------------------------------------
INSERT INTO CORE_MODULO (NOMBRE,DESCRIPCION,ACTIVOENTRADA,ACTIVOSALIDA) VALUES ('AlmacenarBaseDatos','AlmacenarBaseDatos',1,1);
INSERT INTO CORE_MODULO (NOMBRE,DESCRIPCION,ACTIVOENTRADA,ACTIVOSALIDA) VALUES ('ValidarCertificado','ValidarCertificado',1,0);
INSERT INTO CORE_MODULO (NOMBRE,DESCRIPCION,ACTIVOENTRADA,ACTIVOSALIDA) VALUES ('AlmacenarFichero','AlmacenarFichero',1,1);
INSERT INTO CORE_MODULO (NOMBRE,DESCRIPCION,ACTIVOENTRADA,ACTIVOSALIDA) VALUES ('ValidarEsquema','ValidarEsquema',1,1);
INSERT INTO CORE_MODULO (NOMBRE,DESCRIPCION,ACTIVOENTRADA,ACTIVOSALIDA) VALUES ('AlmacenarFicheroPlain','AlmacenarFicheroPlain',1,1);
