<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 sp1 (http://www.altova.com) by End User (free.org) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" targetNamespace="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="DatosEspecificos">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="Consulta"/>
				<xs:element ref="Retorno"/>
			</xs:choice>
			<xs:attribute name="Id" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Consulta">
		<xs:annotation>
			<xs:documentation>Datos de consulta para servicio de obtención de centros universitarios</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="CodigoUniversidad"/>
				<xs:element ref="CodigoCentro" minOccurs="0"/>
				<xs:element ref="FechaDesde" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="Retorno">
		<xs:annotation>
			<xs:documentation>Datos de retorno para servicio de obtención de centros universitarios</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Estado"/>
				<xs:element ref="Centros" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="CodigoCentro">
		<xs:annotation>
			<xs:documentation>Código RUCT del centro</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:whiteSpace value="collapse"/>
				<xs:pattern value="\d{8}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FechaDesde">
		<xs:annotation>
			<xs:documentation>Fecha desde la que se obtendrán las modificaciones de los centros</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:date"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Estado">
		<xs:complexType>
			<xs:all>
				<xs:element name="CodigoEstado">
					<xs:annotation>
						<xs:documentation>Codigo de estado</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="4"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="Literal">
					<xs:annotation>
						<xs:documentation>Descripcion del estado</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:minLength value="1"/>
							<xs:maxLength value="1024"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="Centros">
		<xs:annotation>
			<xs:documentation>Lista de centros obtenidos</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Centro" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Centro">
		<xs:annotation>
			<xs:documentation>Datos del centro obtenido</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="CodigoCentro"/>
				<xs:element ref="NombreCentro"/>
				<xs:element ref="Acronimo" minOccurs="0"/>
				<xs:element ref="Tipo"/>
				<xs:element ref="Situacion"/>
				<xs:element ref="Naturaleza"/>
				<xs:element ref="Direccion" minOccurs="0"/>
				<xs:element ref="CodigoPostal" minOccurs="0"/>
				<xs:element ref="CodigoComunidadAutonoma"/>
				<xs:element ref="CodigoProvincia"/>
				<xs:element ref="Provincia"/>
				<xs:element ref="CodigoLocalidad"/>
				<xs:element ref="Localidad"/>
				<xs:element ref="CodigoUniversidad"/>
				<xs:element ref="Universidad"/>
				<xs:element ref="Telefono" minOccurs="0"/>
				<xs:element ref="Fax" minOccurs="0"/>
				<xs:element ref="Acreditaciones" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="NombreCentro">
		<xs:annotation>
			<xs:documentation>Nombre del centro obtenido</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="150"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Acronimo">
		<xs:annotation>
			<xs:documentation>Acrónimo del centro obtenido</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="10"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Tipo">
		<xs:annotation>
			<xs:documentation>Tipo del centro obtenido</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="1"/>
				<xs:enumeration value="2"/>
				<xs:enumeration value="3"/>
				<xs:enumeration value="4"/>
				<xs:enumeration value="5"/>
				<xs:enumeration value="6"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Situacion">
		<xs:annotation>
			<xs:documentation>Situacion del centro obtenido</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="A"/>
				<xs:enumeration value="B"/>
				<xs:enumeration value="N"/>
				<xs:enumeration value="T"/>
				<xs:enumeration value="P"/>
				<xs:enumeration value="S"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Naturaleza">
		<xs:annotation>
			<xs:documentation>Naturaleza del centro obtenido</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="1"/>
				<xs:enumeration value="2"/>
				<xs:enumeration value="3"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Direccion">
		<xs:annotation>
			<xs:documentation>Dirección del centro obtenido</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="100"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoComunidadAutonoma">
		<xs:annotation>
			<xs:documentation>Código de comunidad autónoma del centro obtenido</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="01"/>
				<xs:enumeration value="02"/>
				<xs:enumeration value="03"/>
				<xs:enumeration value="04"/>
				<xs:enumeration value="05"/>
				<xs:enumeration value="06"/>
				<xs:enumeration value="07"/>
				<xs:enumeration value="08"/>
				<xs:enumeration value="09"/>
				<xs:enumeration value="10"/>
				<xs:enumeration value="11"/>
				<xs:enumeration value="12"/>
				<xs:enumeration value="13"/>
				<xs:enumeration value="14"/>
				<xs:enumeration value="15"/>
				<xs:enumeration value="16"/>
				<xs:enumeration value="17"/>
				<xs:enumeration value="18"/>
				<xs:enumeration value="19"/>
				<xs:enumeration value="60"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoProvincia">
		<xs:annotation>
			<xs:documentation>Código de provincia del centro obtenido</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{2}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Provincia">
		<xs:annotation>
			<xs:documentation>Provincia del centro obtenido</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="25"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoLocalidad">
		<xs:annotation>
			<xs:documentation>Código de localidad del centro obtenido</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{9}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Localidad">
		<xs:annotation>
			<xs:documentation>Localidad del centro obtenido</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="70"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoUniversidad">
		<xs:annotation>
			<xs:documentation>Código de la universidad</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\d{3}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Universidad">
		<xs:annotation>
			<xs:documentation>Universidad a la que pertenece el centro obtenido</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="75"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Telefono">
		<xs:annotation>
			<xs:documentation>Telefono del centro obtenido</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="9"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Fax">
		<xs:annotation>
			<xs:documentation>Fax del centro obtenido</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="9"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CodigoPostal">
		<xs:annotation>
			<xs:documentation>Código postal de la dirección del centro obtenido</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:int">
				<xs:pattern value="\d{5}"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FechaMatriculacion">
		<xs:annotation>
			<xs:documentation>Fecha de matriculación del vehículo consultado</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:date"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Acreditaciones">
		<xs:annotation>
			<xs:documentation>Lista de acreditaciones</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Acreditacion" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Acreditacion">
		<xs:annotation>
			<xs:documentation>Datos de la acreditación del centro</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="CodigoEstado" minOccurs="0"/>
				<xs:element ref="DescripcionEstado" minOccurs="0"/>
				<xs:element ref="FechaRegistro" minOccurs="0"/>
				<xs:element ref="FechaResolucion" minOccurs="0"/>
				<xs:element ref="TipoAcreditacion" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="CodigoEstado">
		<xs:annotation>
			<xs:documentation>Código de estado de la acreditación</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="5"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DescripcionEstado">
		<xs:annotation>
			<xs:documentation>Descripción de estado de la acreditación</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="50"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FechaRegistro">
		<xs:annotation>
			<xs:documentation>Fecha de registro de la acreditación</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:date"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FechaResolucion">
		<xs:annotation>
			<xs:documentation>Fecha de resolución de la acreditación</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:date"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="TipoAcreditacion">
		<xs:annotation>
			<xs:documentation>Tipo de acreditación</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="T"/>
				<xs:enumeration value="I"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>
