<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" targetNamespace="http://intermediacion.redsara.es/scsp/esquemas/datosespecificos" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="DatosEspecificos">
		<xs:complexType>
			<xs:all>
				<xs:element ref="Retorno"/>
			</xs:all>
			<xs:attribute name="Id" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Retorno">
		<xs:annotation>
			<xs:documentation>Datos de retorno para servicio de clases pasivas</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Estado"/>
				<xs:element ref="ClasesPasivas" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Estado">
		<xs:complexType>
			<xs:all>
				<xs:element ref="CodigoEstado"/>
				<xs:element ref="LiteralError"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="CodigoEstado">
		<xs:annotation>
			<xs:documentation>Codigo de estado</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="4"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="LiteralError">
		<xs:annotation>
			<xs:documentation>Descripcion del estado</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="1024"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ClasesPasivas">
		<xs:annotation>
			<xs:documentation>Listado de las clases pasivas devueltas</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ClasePasiva" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ClasePasiva">
		<xs:annotation>
			<xs:documentation>Datos de la calse pasiva obtenida</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element ref="Identificador"/>
				<xs:element ref="TipoJubilacion" minOccurs="0"/>
				<xs:element ref="FechaJubilacion" minOccurs="0"/>
				<xs:element ref="CausanteActivo"/>
				<xs:element ref="FechaArranque" minOccurs="0"/>
				<xs:element ref="FechaFallecimiento" minOccurs="0"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="Identificador">
		<xs:annotation>
			<xs:documentation>Código interno del expediente</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:minLength value="1"/>
				<xs:maxLength value="20"/>
				<xs:whiteSpace value="collapse"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FechaJubilacion">
		<xs:annotation>
			<xs:documentation>Fecha de jubilación</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:date"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="TipoJubilacion">
		<xs:annotation>
			<xs:documentation>Tipo de jubilación</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Forzosa"/>
				<xs:enumeration value="Voluntaria"/>
				<xs:enumeration value="Incapacidad"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="CausanteActivo">
		<xs:annotation>
			<xs:documentation>El causante se encontraba activo en la Fecha de la Jubilación</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Si"/>
				<xs:enumeration value="No"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FechaArranque">
		<xs:annotation>
			<xs:documentation>Fecha de jubilación</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:date"/>
		</xs:simpleType>
	</xs:element>
	<xs:element name="FechaFallecimiento">
		<xs:annotation>
			<xs:documentation>Fecha de fallecimiento</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:date"/>
		</xs:simpleType>
	</xs:element>
</xs:schema>
