ALTER TABLE CORE_EMISOR_CERTIFICADO ADD FECHAALTA TIMESTAMP (6);
ALTER TABLE CORE_TRANSMISION MODIFY ESTADO VARCHAR2(10);

CREATE INDEX CORE_SERVICIO_INDEX_EMISOR  ON CORE_SERVICIO (EMISOR);
CREATE INDEX CESIONARIOS_INDEX_ORGANISMO  ON CORE_REQ_CESIONARIOS_SERVICIOS (ORGANISMO);